### ISSUE TITLE
Error when publishing package migrations

### ISSUE THREAD

**Issue by dambridge** [spatie/laravel-tags#10]
Getting this error:
`Can't locate path: </home/vagrant/my-project/vendor/spatie/laravel-tags/src/../database/migrations/_create_tag_tables.php.stub>`

I suspect the path is incorrect in the service provider?

**Comment by jonfackrell** [comment]
The name of the migration file in the service provider is "_create_tag_tables.php.stub" but the actual name of the file is just "create_tag_tables.php.stub"

**Comment by dambridge** [comment]
@jonfackrell Right you are!

**Comment by freekmurze** [comment]
Thanks for letting me know. This has been fixed in `v1.0.1`
