### ISSUE TITLE
Unable to retrieve tags when using SQLite

### ISSUE THREAD

**Issue by hackel** [spatie/laravel-tags#106]
This could be considered more of a Laravel issue, but I thought I would raise it here in case it seemed worthwhile to work-around it.  Currently, Laravel treats sqlite like any other PDO database, however sqlite doesn't support the "->" shorthand syntax for JSON columns, which means `Tag::findFromString` fails.

e.g.: This fails:
`Tag::findFromString('asdf')` => null
SQL: `select * from "tags" where "name->en" = ? and "type" is null limit 1`

Workaround:
``Tag::whereRaw("json_extract(`name`, '$.en') = 'asdf'")->first()`` => Tag object
SQL: ``select * from "tags" where json_extract(`name`, '$.en') = 'asdf'``

Unfortunately this is causing my integration tests that use an in-memory sqlite database to fail.

**Comment by freekmurze** [comment]
This issue is not caused by this package. Please open up an issue at Laravel.

**Comment by staudenmeir** [comment]
Laravel 5.6.35 supports JSON queries on SQLite (https://github.com/laravel/framework/pull/25328).
