### ISSUE TITLE
How to add tags to searchable array?

### ISSUE THREAD

**Issue by addorange** [spatie/laravel-tags#109]
Hi there,

I adding posts to Laravel Scout by Using the toSearchableArray() method. And now I would like to add the attached tags, too, so I could search them.

Any advice how this could be done?

Thanks.

Chris

**Comment by addorange** [comment]
Nevermind. Sorted it out as I took a look once again at https://github.com/spatie/laravel-tags/issues/107.

Thanks.

**Comment by SamBellerose** [comment]
Can I ask you more details on how you manage to do it?

When I import my data on Algolia I get the value:

```
{
    withTimestamps: false
}
```

For my tags.

Thanks!

**Comment by jayenne** [comment]
I'd like to know if / how to make laravdel-tegs searchable via scout too please.
*Using Collection, Meilisearch & Algolia.

Would anyone have any examples, docs, tips or advice please?

**Comment by jayenne** [comment]
well, that wasn't hard at all :)
You simply create a new model that extends spaties Tag model, then amend your config/tags' `tag_model` 
in my case it was as simple as:
```
<?php

namespace App\Models;

use Laravel\Scout\Searchable;
use Spatie\Tags\Tag as SpatieTag;

class Tag extends SpatieTag
{
    use Searchable;
    protected $table = 'tags';

    /**
         * Get the name of the index associated with the model.
         *
         * @return string
         */
    public function searchableAs()
    {
        return 'tags_index';
    }
}
```
config/tags.php
`'tag_model' => App\Models\Tag::class,`
