### ISSUE TITLE
How to install v1.0 of the same package. 

### ISSUE THREAD

**Issue by SqrFactor** [spatie/laravel-tags#110]
When I install it like "composer require spatie/larave-tags v1.0", it throws this error: 
  Problem 1     - The requested package spatie/larave-tags could not be found in any version , there may be a typo in the package name.  Potential causes: 
 - A typo in the package name  
- The package is not available in a stable-enough version according to your min imum-stability setting    

How can I install v1.0 of laravel-tags in my app? 

Regards

**Comment by faabsen** [comment]
Just simple add the specific version number to the end when executing the command.

`composer require vendor/package:version` just like `composer require spatie/larave-tags:1.0.0`
