### ISSUE TITLE
error adding tags

### ISSUE THREAD

**Issue by navotera** [spatie/laravel-tags#111]
Server version: 10.0.34-MariaDB-0ubuntu0.16.04.1 - Ubuntu 16.04
PHP version: 7.2.3-1

error message : 
`SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '>'$."en"' = ? and `type` is null limit 1' at line 1 (SQL: select * from `tags` where `name`->'$."en"' = tag 1 and `type` is null limit 1)`

script to add tags : 
```
  $myModel = myModel::find(1);
  $myModel->attachTag('tag 1');
```

i suspect that this packages does not support mariadb... or is there somekind of config i missing ???

**Comment by freekmurze** [comment]
You need to use a db that has support for JSON columns (MySQL 5.7 or higher)
