### ISSUE TITLE
Using slugs

### ISSUE THREAD

**Issue by danielwashbrook** [spatie/laravel-tags#112]
Tags module is great! Really appreciate it. Has anyone used the slugs for creating routes? It almost seems like the tag model needs to be extended to use the slug instead of an id by default. But wanted to check in case I'm missing something. I've never worked with locale and slugs in json before. Thanks!

Something like:
`Route::get('/productsbytag/{tag}', ['as'=>'product.productsbytag','uses' => 'ProductController@productsByTag']);`

But then I think the Tag model needs:
`
public function getRouteKeyName()
  {
    return 'slug->en';
  }
`
Right?

**Comment by Rattone** [comment]
Apologies for reopening this old issue, I have the same problem, I need to use slugs to create my blog's route for tags.
Is it possible to do it with this library? Because I have not yet succeeded. Am I missing something?
What's the point of having a slug if not for clean urls?

**Comment by mannyarmghan** [comment]
For anyone else having this issue:
It is mentioned in the config file, the models name is "tag_model"

So it would be like
Route::get('/{tag_model:slug}', [Controller::class, 'method']);
