### ISSUE TITLE
[Feature request] Similar by tags

### ISSUE THREAD

**Issue by satoved** [spatie/laravel-tags#114]
Hello and thanks for a great package.

Do you think it's possible to create something like

    YourModel::withSimilarTags(['tag 1', 'tag 2'])->get();

Which will return models with most tags intersecting number? (will order them by intersected tags count)

Great functions to show "similar items" for practically anything.

**Comment by freekmurze** [comment]
It's certainly possible to create a function that does that.

I'd like to keep the package as simple as can be, so code that function up in your own project. 👍

**Comment by noxify** [comment]
@satoved maybe a bit too late, but here the snippet how I solved this:

```
Article::published()->withAnyTags($article->tags)->where('id', '!=', $article->id)->inRandomOrder()->take(3)->get()
```
