### ISSUE TITLE
How to get a count of tag usage

### ISSUE THREAD

**Issue by cicsolutions** [spatie/laravel-tags#115]
Hello, and thank you for all you do for the development community!

I have your tags trait applied to my Post model, and I'm curious how I can get a count of how many posts are using a given tag.  Ultimately, I'd like to display the tags in the order of which tags are used the most.  

I'm wondering if there is a quick way to get the tag usage counts.  Eloquent allows for counting relationships, but the following approach isn't working, probably because the relationship doesn't exist on the Tag model.

`$tags = Tag::withCount('posts')->get()`

My thinking is I would get the additional column in the collection for post_count, and then I could order the collection by the post counts.

I suppose I could use my own Tag model class, as your documentation outlines.  But initially, that feels like an overly complicated way of getting my hands on the tag usage counts.  

Is there a method baked into the laravel-tags trait that I'm not seeing in the documentation?  Would you be able to assist me in figuring this out?

Again, thanks so much!  I'm really glad I found Spatie!

**Comment by freekmurze** [comment]
Thank you for your kind words, I'm glad you find our stuff useful. I think the way to go would be to use a custom model and introduce the functions you need there. 

If you need help with the actual query, it's best to post a question on a public forum like Laracasts of Laravel.io

Happy coding!

**Comment by sixpeteunder** [comment]
@cicsolutions did you ever find an good way to do this? I was able to write a very inefficient query that loops over all the tags but I worry about how it will perform as the database grows.

**Comment by leknoppix** [comment]
> Hello, and thank you for all you do for the development community!
> 
> I have your tags trait applied to my Post model, and I'm curious how I can get a count of how many posts are using a given tag. Ultimately, I'd like to display the tags in the order of which tags are used the most.
> 
> I'm wondering if there is a quick way to get the tag usage counts. Eloquent allows for counting relationships, but the following approach isn't working, probably because the relationship doesn't exist on the Tag model.
> 
> `$tags = Tag::withCount('posts')->get()`
> 
> My thinking is I would get the additional column in the collection for post_count, and then I could order the collection by the post counts.
> 
> I suppose I could use my own Tag model class, as your documentation outlines. But initially, that feels like an overly complicated way of getting my hands on the tag usage counts.
> 
> Is there a method baked into the laravel-tags trait that I'm not seeing in the documentation? Would you be able to assist me in figuring this out?
> 
> Again, thanks so much! I'm really glad I found Spatie!

Good evening

I found a solution, however, it is not optimizing at all.

The idea is to list the tags, and use a fractal transformation to execute a second query per tag.
Here is my code if it can inspire some.

```php
<?php
$tags = Tag::take(10)->get();
$tags = fractal($tags, new TagTransformer())->toArray();
dd($tags['data']);
```

And my transformer:
```php
<?php

namespace App\Transformers;

use App\Models\Post;
use League\Fractal\TransformerAbstract;
use Spatie\Tags\Tag;

class TagTransformer extends TransformerAbstract
{
    /**
     * A Fractal transformer.
     *
     * @return array<string,string|int>
     */
    public function transform(Tag $tag)
    {
        $count = (int) Post::published()->WithTagSlug($tag->slug, 'App\Models\Post')->count();
        return [
            'name' => $tag->name,
            'slug' => $tag->slug,
            'count' => $count
        ];
    }
}
```

The problem I have in my case, is that the more tags you have, the more requests you have.

Again, thank you very much for this package, as for the others.

**Comment by benjamintemitope** [comment]
To get the count of each tag and order them by the highest count, follow these steps:

1. Create a new model to extend `Spatie\Tags\Tag`. (You can name your model `Tag`).
```php
<?php

namespace App\Models;

use App\Models\Post;
use Spatie\Tags\Tag as SpatieTag;

class Tag extends SpatieTag
{
    public function posts()
    {
        return $this->morphedByMany(Post::class, 'taggable');
    }
}
```

2. Retrieve the tag counts and order them by usage in descending order:
```php
use App\Models\Tag;

$tags = Tag::withCount('posts')->orderBy('posts_count', 'desc')->get();
```

[Reference](https://github.com/spatie/laravel-tags/issues/94#issuecomment-447294759)
