### ISSUE TITLE
Can I somehow use scopes on a query builder instance?

### ISSUE THREAD

**Issue by tnorthcutt** [spatie/laravel-tags#118]
I have some existing code that filters a model, like so:

```
$member = $member->newQuery() // $member is an instance of \App\Models\Member
$member->where('some relation here');
```
I want to be able to add tag filtering to this existing code (the `Member` model uses `HasTags`). This obviously doesn't work, but something like this:
```
$member->withAllTags('tagname');
```

Is there a "correct" way to go about this, without completely reimplementing the `scopeWithAllTags()` method in my code, or changing my code to not use a query builder instance?

**Comment by freekmurze** [comment]
I'm thinking that `withAllTags` is a scope so you can tack on any extra claused that you want.

This should work: 
```
Member::withAllTags(['tag1', 'tag2'])->where('your_field', $yourValue)->get();
```

**Comment by tnorthcutt** [comment]
_Sharing this for posterity, in case others (or more likely, a future me) seek this same functionality._

Turns out the code that does what I wanted was this:

```
$member->scopes([
    'withAllTags' =>'tagname'
]);
```

This takes advantage of the `\Illuminate\Database\Eloquent::scopes()` method.
