### ISSUE TITLE
Retreive all tags given to model

### ISSUE THREAD

**Issue by martinetoye** [spatie/laravel-tags#119]
Hi.

How can I retrieve all tags given to a model. 

I know you can retrieve a Model with given tags using withAnyTags() or withAllTags(). But I want to retrieve all tags given to a model. 

e.g Post 1 has 4 tags attached to it.

Thanks

**Comment by freekmurze** [comment]
That easy, you can do that with `$model->tags`.

**Comment by maganius** [comment]
im trying get all tags from a `mutator` but it return always null
```
public function getTagsAttribute($value){
        dd($this->getOriginal('tags'), $this->tags()->containing('pymes')->get(), $value);
//        return $this->tags->implode(',');
}
```

returned:

```
null

Collection {#645 ▼
  #items: []
}

null
```

The tag pymes exists in database, `$this->tags` also return null.
