### ISSUE TITLE
Creating tag with type throws exception

### ISSUE THREAD

**Issue by lasselehtinen** [spatie/laravel-tags#12]
Hi,

Awesome package, but I am having trouble using the types. There is one thing that don't seem to work:

`$tag = Tag::create($characteristic, 'beerCharacteristicTag');`

returns the following error:

```
[Symfony\Component\Debug\Exception\FatalThrowableError]

Type error: Argument 1 passed to Illuminate\Database\Eloquent\Model::create() must be of the type array, string given, called in /home/vagrant/Code/beer/app/Console/Commands/ScrapeBeers.php on line 121
```
where as `$tag = Tag::findOrCreate($characteristic, 'beerCharacteristicTag');` works just like it should.

PS. There is a small typo in the documentation. Double colon instead of semi.

`$tagWithType = Tag::create('headline', 'newsTag'):`

**Comment by freekmurze** [comment]
For tag creation you should only use the `findOrCreate` method. That method has support for creating tags of a certain type and will make sure that no duplicate tags are created. The `create` method is just the plain eloquent method. It has no knowledge about the rest of the functionality of the package.

Thanks for letting me know there was a typo. Fixed.

**Comment by lasselehtinen** [comment]
Well that makes sense, I thought the package was doing some magic by extending the create method on the Eloquent model. But you have this exact example [in the documentation](https://docs.spatie.be/laravel-tags/v1/advanced-usage/using-types), which I assume is a mistake then?

    //creating a tag with a certain type
    $tagWithType = Tag::create('headline', 'newsTag');

**Comment by lasselehtinen** [comment]
Well that makes sense, I thought the package was doing some magic by extending the create method on the Eloquent model. But you have this exact example [in the documentation](https://docs.spatie.be/laravel-tags/v1/advanced-usage/using-types), which I assume is a mistake then?

    //creating a tag with a certain type
    $tagWithType = Tag::create('headline', 'newsTag');

**Comment by lasselehtinen** [comment]
Well that makes sense, I thought the package was doing some magic by extending the create method on the Eloquent model. But you have this exact example [in the documentation](https://docs.spatie.be/laravel-tags/v1/advanced-usage/using-types), which I assume is a mistake then?

    //creating a tag with a certain type
    $tagWithType = Tag::create('headline', 'newsTag');

**Comment by freekmurze** [comment]
That's a mistake indeed, thanks for bringing that to my attention. I've update the example.

**Comment by freekmurze** [comment]
That's a mistake indeed, thanks for bringing that to my attention. I've update the example.
