### ISSUE TITLE
detachTag is not detaching tags

### ISSUE THREAD

**Issue by christopheelkhourysaradar** [spatie/laravel-tags#120]
**Scenario:**
I have a Tagged Model whose tag I am trying to detach.

**Actual Behavior:**
When I detach the tag from the model and fetch the model again, the model along with the tag is always returned

**Expected Behavior:**
When I detach the tag from the model and fetch the model again, the model should return an empty `tags` property or no `tags` property at all

**What I've tried doing:**
```
$model = Model::find(1)->first();
$model->tag('Tag Name');
 
// Now model is returned with the Tag. To delete it:

$model->detachTag('Tag Name'); // Doesn't work
$model->detachTags(['Tag Name']); //Doesn't work
$model->detachTag(1); // Thinking it might work with the Tag's ID, doesn't work
```

Any help would be greatly appreciated. Thanks!

**Comment by freekmurze** [comment]
The tests prove that detachTag is working: https://github.com/spatie/laravel-tags/blob/5d8216d490eabbf0e98b385472b30af233652795/tests/HasTagsTest.php#L100-L118

Could you please PR a failing test for us to look at?

**Comment by christopheelkhourysaradar** [comment]
Turns out it's a problem from my terminal. I apologize for the inconvenience. :)

Thank you for the quick reply @freekmurze !

Closing as Not an Issue.
