### ISSUE TITLE
Don't create non-existing tags if not allowed when using sync

### ISSUE THREAD

**Issue by francoism90** [spatie/laravel-tags#122]
```
public function syncTags($tags)
    {
        $className = static::getTagClassName();

        $tags = collect($className::findOrCreate($tags));

        $this->tags()->sync($tags->pluck('id')->toArray());

        return $this;
    }
```

Maybe something like this would be great: `$model->syncTags([..], false);`:
```
public function syncTags($tags, $createNonExists = true)
{
...
}
```

Thanks. :)

**Comment by freekmurze** [comment]
I don't want to have a boolean argument in the `syncTags` function as boolean arguments are often not really readable.

I'd accept a fully tested and documented PR that adds a `syncExistingTags` that doesn't create new tags.
