### ISSUE TITLE
Add timestamp to taggables table to track when a tag was attached to a model

### ISSUE THREAD

**Issue by jonagoldman** [spatie/laravel-tags#124]
Is it possible to add a `created_at` column to the `taggables` table in order to know when a specific tag was attached to a model?

**Comment by freekmurze** [comment]
Yes, just add the `created_at` field to the taggables table. Next override the `tags` function by just defining it in your model. Tack on `->withTimestamps()` to the query. https://laracasts.com/discuss/channels/eloquent/created-at-field-with-pivot-table-and-attach-method
