### ISSUE TITLE
attachTag creates an extra row in the database

### ISSUE THREAD

**Issue by lasselehtinen** [spatie/laravel-tags#13]
Seems like attachTag is acting strangely. It seems to create an additional line, which includes the data for the whole model, not just the tag.

```
foreach ($characteristics as $characteristic) {
    $tag = Tag::findOrCreate($characteristic);
    $beer->attachTag($tag);
}
```

![image](https://cloud.githubusercontent.com/assets/1290186/19874321/ee1d129c-9fcc-11e6-8d42-201f00cec4a3.png)

Using `$beer->syncTags($characteristics);` is the workaround but I would like to attach typed tags and you cannot use syncTags for that one.

**Comment by freekmurze** [comment]
This bug has been fixed in the newly tagged release `1.0.2`.
