### ISSUE TITLE
MariaDb 10.2 issue

### ISSUE THREAD

**Issue by avasiliev87** [spatie/laravel-tags#131]
I got following issue when I called attachTag method. ( MariaDb 10.2 )

$video->attachTag('historical');

Illuminate/Database/QueryException with message 'SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '>'$."en"' = ? and `type` is null limit 1' at line 1 (SQL: select * from `tags` where `name`->'$."en"' = historical and `type` is null limit 1)'

**Comment by freekmurze** [comment]
This package supports only MySql 5.7 or higher

**Comment by avasiliev87** [comment]
Would you rename your package something like "laravel-tags-mysql"?

**Comment by avasiliev87** [comment]
Actually, I am really thanks to your package, but really want to use in my application

**Comment by daniwb** [comment]
If you are still searching for a Solution, check this Commit:
https://github.com/spatie/laravel-tags/commit/a8e18ac6176d853c1cbcfa1a213b895ed305b565
