### ISSUE TITLE
Mariadb 10.2 issue

### ISSUE THREAD

**Issue by avasiliev87** [spatie/laravel-tags#132]
I am running laravel project with mysql 10.2.
I got following error when I am trying to create tag.

Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '>'$."en"' = ? and `type` = ? limit 1' at line 1 (SQL: select * from `tags` where `name`->'$."en"' = historical and `type` = animation limit 1)

**Comment by freekmurze** [comment]
Please use MySQL.

**Comment by daniwb** [comment]
If you are still searching for a Solution, check this Commit:
https://github.com/spatie/laravel-tags/commit/a8e18ac6176d853c1cbcfa1a213b895ed305b565

**Comment by BobbyBorisov** [comment]
@daniwb how is this commit solving the problem? it still throws an error when doing artisan migrate
