### ISSUE TITLE
10.2.13-MariaDB support plz

### ISSUE THREAD

**Issue by guoxiangke** [spatie/laravel-tags#134]
I met blow error: & test https://github.com/Inggo/laravel-tags/commit/dc551a2261f5525e527ebb89b55acb3d98f9acfe works , thanks.

QueryException(code: 42000): SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '>'$.\"en\"' = ? and `type` is null limit 1' at line 1 (SQL: select * from `tags` where `name`->'$.\"en\"' = tets and `type` is null limit 1) at /Users/dale/Sites/laravel/docker-wechat/laravel/vendor/laravel/framework/src/Illuminate/Database/Connection.php:664, Doctrine\\DBAL\\Driver\\PDOException(code: 42000): SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '>'$.\"en\"' = ? and `type` is null limit 1' at line 1

**Comment by freekmurze** [comment]
We only support MySQL

**Comment by miharbi** [comment]
You have to install this package https://github.com/ybr-nx/laravel-mariadb it solved my problem.

**Comment by guoxiangke** [comment]
@miharbi great thanks, I'll have a try,
