### ISSUE TITLE
Possible to Tag::getWithType and list tags alphabetically?

### ISSUE THREAD

**Issue by lmartins** [spatie/laravel-tags#135]
I was looking to get all tags of a specific type, with something like `Tag::getWithType('type_name')` but would also need the collection that is given to be sorted alphabetically? Is there any way to achieve that?

Ideally, I would prefer on my use case to set that order as the default at the Tag model level, but something done at request would work too.

Thank you!

**Comment by freekmurze** [comment]
`Tag::getWithType('type_name')` returns a collection. So you can just sort it by calling `sortBy` on it.
