### ISSUE TITLE
How to create new tag with Type ?

### ISSUE THREAD

**Issue by sergeynilov** [spatie/laravel-tags#138]
Hello,
I added spatie/laravel-tags("spatie/laravel-tags": "^2.1",) plugin 
to my Laravel 5.7 and working with it I did not find some things, like:

1) I see that tags tables has "type" field. 
I fill my data with code like : 
```
 $newsItem = NewsItem::create(
   [ 'name' => 'testModel', 
     'tags' => ['tag', 'tag2'], //tags will be created if they don't exist 
   ]
   ); 
```
     
But I did not find how adding new tags assign some type for them ? 

2) I did not find if there is a method to searcg by slug, like :
```
        $activeTag = Tag::findBySlug( $tag_slug );
```
?

Thanks!

**Comment by freekmurze** [comment]
On the documentation there are a few examples on how to work with tag types: https://docs.spatie.be/laravel-tags/v2/advanced-usage/using-types

A `Tag` is just an Eloquent model, so you could manually update `type` on it, should you want to.
