### ISSUE TITLE
 SQLSTATE[42000]: Syntax error or access violation: 1064 #72

### ISSUE THREAD

**Issue by desidude03** [spatie/laravel-tags#139]
i am getting the folowing error when i am running.
PHP artisan Migrate comman in Laravel CLI or composer

**Comment by desidude03** [comment]
most i can't find "spatie/laravel-tags" in the laravel directory and neither those are available in CLI

**Comment by freekmurze** [comment]
Make sure you are running MySQL 5.7 or higher, other database are not supported.

**Comment by daniwb** [comment]
If you are still searching for a Solution, check this Commit:
https://github.com/spatie/laravel-tags/commit/a8e18ac6176d853c1cbcfa1a213b895ed305b565

**Comment by funkju** [comment]
Will this commit be added to master? It fixes the 1064 error for me as well. Running MariaDB on MacOS

**Comment by BobbyBorisov** [comment]
@daniwb what is the best way to use your solution for MariaDB? Fork the repo and apply the change? Hey @freekmurze, thanks for all the packages! Would you consider adding this feature to the main repo? Cheers from Bulgaria!

**Comment by freekmurze** [comment]
@freekmurze thanks!

No, I like to keep te more readable version of the code. I don't need MariaDB compatibility for my projects. Feel free to fork the code!

**Comment by mmjjb** [comment]
@freekmurze I understand your view. 

I just hope you will add MariaDB compatibility in the future. 
Over the last years more projects and OS's use MariaDB by default.
