### ISSUE TITLE
cannot use withAllTags with array of different tag and tag types

### ISSUE THREAD

**Issue by FutureFutureTo** [spatie/laravel-tags#143]
Been trying tp figure out of there is a way to do this:

```
$tag1 = Tag::create('tag1', 'newsItem');
$tag2 = Tag::create('tag2', 'differentNewItem');

Model::attachTag($tag1);
Model::attachTag($tag2);

$model = Model::withAllTags($tag1, $tag2);

return $model;
```

I can see that the withAllTags function is taking in a list of tags, and only one type....Any way we could switch this to accept an array of $tag => $type??

**Comment by taliptako** [comment]
And even it should accept array of tag ids because otherwise its mean you're sending one extra query..

**Comment by freekmurze** [comment]
We're going to keep things as they are for now. If you need some custom method behaviour just create your own tag model extending ours and put your functions there.
