### ISSUE TITLE
The Developer should be able to choose the way how slugs will be generated

### ISSUE THREAD

**Issue by mehranrasulian** [spatie/laravel-tags#15]
Hi!
As you may know, `HasSlug` trait will generate slug for tags just using `str_slug` method that will be used just for English and left-to-right languages but not anyone's native language is English.

So I've added the ability to choose which method to use when generating slugs, in https://github.com/spatie/laravel-tags/pull/14 PR

**Comment by freekmurze** [comment]
We'll discuss this further in #14

**Comment by freekmurze** [comment]
Thanks for your work on this. The changes are part of the newly released version `1.1.0`.

**Comment by mehranrasulian** [comment]
I hope to collaborate more on Spatie.
