### ISSUE TITLE
(boolean) HasTag($tag)?

### ISSUE THREAD

**Issue by StanBarrows** [spatie/laravel-tags#151]
Heyho, 

Is there a specific way to check if a model has a specific Tag ?

```
 $boolean = $model->hasTag($tag)
 $boolean =  $model->hasTag('slug')
```
Could not find it within the documentation.

Cheers, Stan

**Comment by freekmurze** [comment]
Currently not, but you can easily add that function to your own model.

**Comment by freekmurze** [comment]
Currently not, ... but I'll revisit this ticket when creating a new major release.

**Comment by Sentoki** [comment]
No such method yet?
