### ISSUE TITLE
Scopes only working when I pass it `tag` instance

### ISSUE THREAD

**Issue by mokhosh** [spatie/laravel-tags#154]
`withAnyTags` and `withAllTags` scopes only work when I pass them `tag` instances, and don't work when I pass them strings.

I have a tag called 'unreliable' which is attached to two `User`s. but this returns an empty collection:
```php
User::withAnyTags('unreliable')->get();
User::withAnyTags(['unreliable'])->get();
```

**Comment by mokhosh** [comment]
Ok I found my problem. I have specified `types` for my tags, but there is no way to search for tags without specifying their type.

There has to be a way to find tags of any type that match the name. I'm using `laravel-query-builder` and I don't think there's any way I can pass a type to the scope through its query strings.

**Comment by freekmurze** [comment]
First thought: you can add custom search logic by creating custom filter:
https://github.com/spatie/laravel-query-builder#custom-filters

**Comment by mokhosh** [comment]
That's actually what I did. But I don't think this issue is only related to `query-builder`. Don't you agree that it's a common use case where we need to find a tag regardless of its type?

**Comment by freekmurze** [comment]
I'm thinking the easiest way to find items that have tags of a certain type, would be to retrieve those tag instances first and pass those to `withAnyTags`. 

I would accept a PR that adds a `withAnyTagsOfAnyType` scope to the package.

**Comment by freekmurze** [comment]
We'll continue this in #157
