### ISSUE TITLE
Autosuggest not working with tags for postgresql

### ISSUE THREAD

**Issue by faizaajmal** [spatie/laravel-tags#158]
Autosuggest not working with tags for postgresql.

SQLSTATE[42883]: Undefined function: 7 ERROR: function json_extract(json, unknown) does not exist LINE 1: select * from "tags" where LOWER(JSON_EXTRACT(name, '$."en"'... ^ HINT: No function matches the given name and argument types. You might need to add explicit type casts. (SQL: select * from "tags" where LOWER(JSON_EXTRACT(name, '$."en"')) like "%office%" and "type" = property_type and "type" = property_type limit 5)

**Comment by freekmurze** [comment]
This package only supports `MySQL`
