### ISSUE TITLE
updating to 2.2.0 brokes compatibility with laravel 5.5

### ISSUE THREAD

**Issue by Briareos17** [spatie/laravel-tags#161]
After trying to install latest version I getting composer error:

> Your requirements could not be resolved to an installable set of packages.
>
>  Problem 1
>    - Installation request for spatie/laravel-tags 2.2.0 -> satisfiable by spatie/laravel-tags[2.2.0].
>    - spatie/laravel-tags 2.2.0 requires laravel/framework ~5.7.13 -> satisfiable by laravel/framework[5.7.x-dev, v5.7.13, v5.7.14, v5.7.15, v5.7.16, v5.7.17, v5.7.18, v5.7.19] but these conflict with your requirements or minimum-stability.

But documentation says that 5.5 fully supported by 2.x

**Comment by xenonthong** [comment]
Similar issue here. Using 2.1.* for now.

**Comment by freekmurze** [comment]
Thank you for bringing this to my attention, I'll update the docs.

[Starting from 2.1.6](https://github.com/spatie/laravel-tags/blob/2.1.6/composer.json#L20) we did drop support for Laravel 5.5. Dropping support for older packages and frameworks within one major version isn't a breaking change. 

Composer is trying to protect you from installing a version that won't work in your application. That's a good thing.
