### ISSUE TITLE
[Question] The slug of other languages changes

### ISSUE THREAD

**Issue by sdr0x07b6** [spatie/laravel-tags#162]
Hi,

---
```
$tag = Tag::findOrCreate(['name' => 'my tag']);
$tag->setTranslation('name', 'fr', 'mon tag');
$tag->save();
```

tags table
```
name: { "ja": "my tag", "fr": "mon tag" }
slug: { "ja": "my-tag", "fr": "mon-tag" }
```
---
```
$tag->update(['name' => 'test']);
```

tags table
```
name: { "ja": "test", "fr": "mon tag" }
slug: { "ja": "test", "fr": "test" }
```
---
The `name` of `"fr"` does not changed by `update()`.
However, the `slug` of `"fr"` has changed.
Is this correct behavior?

**Comment by sdr0x07b6** [comment]
Regardless of the language, if slug is unique, I thought that slug should not be saved for each language.🤔

**Comment by freekmurze** [comment]
When working with translations it's probably best to not use `update` on a tag but `setTranslation`.
