### ISSUE TITLE
no such function: json_extract when testing attachTags method

### ISSUE THREAD

**Issue by connor11528** [spatie/laravel-tags#166]
Hi there, Thanks for the package. Everything is working great I'm using MySQL for local and in production. I am writing a test to verify my code works but is failing due to SQLite limitations about `no such function: json_extract`.

Is there a way to write tests for code that use this package? I see in the **tests** folder you're using Docker to fire up mysql for tests, maybe that's the best approach?

Here is my test:
```
/** @test */
public function submitting_form_updates_user()
{
    $this->withoutExceptionHandling();

    $user = factory(User::class)->states('active')->create();

    $this->actingAs($user)->put('/candidates/' . $user->id . '/edit', [
        'summary'            => 'I am a programmer with Laravel and Vue',
        ...
        'tags'               => ['Laravel', 'Vue.js']
    ]);
```

Then in my controller I attach the tags to the user:

```
$tags = $request->input('tags');
$user->attachTags($tags);

$user->save();
```

The attachTags method is throwing an error:

```
Illuminate\Database\QueryException: SQLSTATE[HY000]: General error: 1 no such function: json_extract (SQL: select * from "tags" where json_extract("name", '$."en"') = Laravel and "type" is null limit 1)
...
Caused by
Doctrine\DBAL\Driver\PDOException: SQLSTATE[HY000]: General error: 1 no such function: json_extract
```

Possibly related to #106

**Comment by solarsoft0** [comment]
Currently facing this issue, @connor11528 where you able to fix it

**Comment by connor11528** [comment]
@solarsoft0 I was not. Since they have tests written for this package I'm relying on those and not performing `attachTags` action in my test, assuming it works. It's a limitation on SQLite and I was too lazy to set MySQL for testing

**Comment by ams-ryanolson** [comment]
I want to say we are also having the same issue - if anyone comes across a solution please let me know and we will do the same as well.
