### ISSUE TITLE
Taggables table has no indexing

### ISSUE THREAD

**Issue by robbydooo** [spatie/laravel-tags#169]
Our website has jus gone crazy slow after we had inserted a lot of related models to tags. There are 3.5 million records in the taggables table. Queries are taking more than 2 minutes to load.

Upon closer inspection I see that there are no indexed fields in the taggables table.
Is there a reason for this? 

I cant think of any off the top of my head but it seems like such a major issue I am wondering why no one else has picked up on this?

**Comment by freekmurze** [comment]
That's quite a lot of taggables 😄 

In most packages we don't add any indexes, because sometimes they are not wanted.

Feel free to update our readme with a tip on the indexes you added to solve your problem.

**Comment by AidasK** [comment]
Have you figured it out how to add an index for this json column @robbydooo ?
