### ISSUE TITLE
Load the tags as an array without translations

### ISSUE THREAD

**Issue by scottybo** [spatie/laravel-tags#171]
I'd like to return an array of tags without the nested name and language attributes. Loading the tags is nice and easy:

```php
// Load the files
$files = Media::all();

// Load the tags, only returning the name column
$files->load(['tags' => function ($query) {
     $query->select('name');
}]);
```
As we know, the `name` column in `tags` is a json encoded object.

Instead of having the nested `name->en`, I'd just like an array of all the tags (we're not using the language functionality) in the format of
```php
['tag1', 'tag2']
```
I can do this using the horrible code below:
```php
// Remove the tag object with all the variables (e.g. 'en') and just return an array of tags
foreach($files as $i => $file) {
    $tag_array = [];

    foreach($file->tags as $tag) {
        $tags_decoded = json_decode($tag);
        $tag_array[] = $tags_decoded->name->en;
    }

    unset($files[$i]->tags);
    $files[$i]['media_tags'] = $tag_array;
}
            
 
return response()->json([
    'files' => $files
]);
```

But I was hoping there was a better way of doing this which wasn't so hacky. Any ideas?

**Comment by solarsoft0** [comment]
yeah i think you can try this too, it will give you the default locale for your app

` public function toArray()
{
    $attributes = parent::toArray();
    foreach ($this->getTranslatableAttributes() as $name) {
        in_array($name, array_keys($attributes), true) ?
        $attributes[$name] = $this->getTranslation($name, app()->getLocale()) :
        '';
    }
    return $attributes;
}
`

**Comment by joebenson** [comment]
@scottybo I recently wrote a PR that might help. @freekmurze was kind enough to merge it into 2.4.0. See https://github.com/spatie/laravel-tags/pull/175 for details.
