### ISSUE TITLE
Retrieve all models that their tags belong to a type

### ISSUE THREAD

**Issue by Xoshbin** [spatie/laravel-tags#173]
Is it possible to Retrieve all models that their tags belong to a type. If it's not clear what I mean is let's say I have a news model and every news is tagged and to categorize the tags and retrieve the news based on the type not the tags. something like that:
`Tag::getWithType('firstType');`
but instead of returning the tags in the type, return every news that their tags belong to the "firstType".

> News::getWithType('firstType');

**Comment by Rezrazi** [comment]
A quick workaround for that would be :
```php
return News::withAnyTags(
   Tag::getWithType('firstType')->pluck('name')->toArray()
   , 'firstType')->get();
```

not the prettiest nor the most cost effective, but it works.
The issue here is that withAnyTags doesn't take an empty array as first argument, might submit a PR for that if I have time.
