### ISSUE TITLE
Question about compatibility

### ISSUE THREAD

**Issue by chriskonnertz** [spatie/laravel-tags#174]
Hello,

thank you for creating and maintaining this great library.

Please can you confirm that I can safely update from version 1.4.1 to 2.0.1 if the requirements (Laravel version) are met?

**Comment by freekmurze** [comment]
A major version means there are breaking changes. I don't know the specific breaking changes by heart. I'm thinking most of the stuff should still work.

**Comment by chriskonnertz** [comment]
Thanks!
