### ISSUE TITLE
Grouping tags instead of rows for each record for the same Taggable

### ISSUE THREAD

**Issue by Rezrazi** [spatie/laravel-tags#176]
### Current behavior
When attaching a tag to a taggable, a new row is appended to the `taggables ` table.
In case where you have a large number of taggable models, and a large number of tags to be assigned, this might cause a performance and size issue for the database.

### Suggested behavior
I know the package makes use of the Laravel `$this->attach()` method, but would it possible to come around it and have an alternative for it ?

**Comment by freekmurze** [comment]
It there is a simple, readable and testable alternative, I'd accept a PR for it.

**Comment by Rezrazi** [comment]
Upon analysis, even if the Laravel attach method is not cost effective on the database when facing large count of entries, but it's the best of the worst, since this package allows queries in both ways, ie. getting models from tags and inversely tags from models, it won't be possible to group entries based on `tag_id` or `taggable_id` since there's no criteria to choose either of them. 

For now I will make peace with the devil and make my database ready for the use case. 🤷‍♂️
