### ISSUE TITLE
Problem when install this package with Laravel v5.7.28

### ISSUE THREAD

**Issue by shalawani** [spatie/laravel-tags#179]
vagrant@homestead:~/code/istakteb$ composer require spatie/laravel-tags
Using version ^2.3 for spatie/laravel-tags
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Can only install one of: laravel/framework[v5.7.28, 5.8.x-dev].
    - Can only install one of: laravel/framework[5.8.x-dev, v5.7.28].
    - Can only install one of: laravel/framework[5.8.x-dev, v5.7.28].
    - spatie/eloquent-sortable 3.5.0 requires laravel/framework ~5.8.0 -> satisfiable by laravel/framework[5.8.x-dev].
    - spatie/laravel-tags 2.3.0 requires spatie/eloquent-sortable ^3.5 -> satisfiable by spatie/eloquent-sortable[3.5.0].
    - Installation request for spatie/laravel-tags ^2.3 -> satisfiable by spatie/laravel-tags[2.3.0].
    - Installation request for laravel/framework (locked at v5.7.28, required as 5.7.*) -> satisfiable by laravel/framework[v5.7.28].

Installation failed, reverting ./composer.json to its original content.

**Comment by Rezrazi** [comment]
As per 20ca99dbb81d2d23adb4e310f1c9c388dc0a0743 the package has dropped support for Laravel `5.7` and PHP `7.1` and below.
Please upgrade your Laravel to 5.8, more info : https://laravel.com/docs/5.8/upgrade

**Comment by phoenixg** [comment]
I hope it can support PHP 7.1
