### ISSUE TITLE
Using your own tag model

### ISSUE THREAD

**Issue by jonfackrell** [spatie/laravel-tags#18]
I might be doing something wrong here, but the documentation references using your own tag model. I've overridden the get TagClassName method: 

```php
use Illuminate\Database\Eloquent\Model;

class YourModel extends Model
{
   public static function getTagClassName(): string
   {
       return YourTagModel::class;
   }
}
```

However, in the tags method the code still refers to the Tag::class:

```php
public function tags(): MorphToMany
{
        return $this
            ->morphToMany(Tag::class, 'taggable')
            ->orderBy('order_column');
}
```

Is this intentional and I need to override this method as well or should it use my custom Tag Model?

Thanks

**Comment by freekmurze** [comment]
Hi,

thanks from bringing this to my attention. It's a bug. I've fixed it in the newly tagged version `1.1.1`.
