### ISSUE TITLE
Can't install under Laravel 5.7

### ISSUE THREAD

**Issue by Tjoosten** [spatie/laravel-tags#184]
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Can only install one of: laravel/framework[v5.7.28, 5.8.x-dev].
    - Can only install one of: laravel/framework[5.8.x-dev, v5.7.28].
    - Can only install one of: laravel/framework[5.8.x-dev, v5.7.28].
    - spatie/eloquent-sortable 3.5.0 requires laravel/framework ~5.8.0 -> satisfiable by laravel/framework[5.8.x-dev].
    - spatie/laravel-tags 2.4.1 requires spatie/eloquent-sortable ^3.5 -> satisfiable by spatie/eloquent-sortable[3.5.0].
    - Installation request for spatie/laravel-tags ^2.4 -> satisfiable by spatie/laravel-tags[2.4.1].
    - Installation request for laravel/framework (locked at v5.7.28, required as 5.7.*) -> satisfiable by laravel/framework[v5.7.28].

Installation failed, reverting ./composer.json to its original content.

**Comment by freekmurze** [comment]
Try installing laravel-tags v2.2.2 or below
