### ISSUE TITLE
Works with L5.8 only?

### ISSUE THREAD

**Issue by msurguy** [spatie/laravel-tags#185]
Hello and thank you for this package! 

I'm having the following error when trying to install this package on L 5.7:

<img width="1074" alt="Screen Shot 2019-03-16 at 8 32 31 AM" src="https://user-images.githubusercontent.com/585833/54477540-100e9a80-47c6-11e9-88b2-b9cfb7bbb34f.png">

Is there something I can do to make it work on L5.7?

**Comment by freekmurze** [comment]
Try requiring version 2.2.1 of our package, it still supports L5.7.
