### ISSUE TITLE
Question - How to extend the tags model?

### ISSUE THREAD

**Issue by devchops** [spatie/laravel-tags#19]
Hi,

Ive set up this package and its been very easy to install and use, so thank you for building it and sharing it 👍 

I have gone through the docs on [extending the model](https://docs.spatie.be/laravel-tags/v1/advanced-usage/using-your-own-tag-model) for this package, but I am not sure how it would actually be implemented. Can you provide more details in the example (here or in the docs) ?

My objective is to extend the tags so the user can add a "color" for each tag (color makes it easy to identify tags, similar to gmail). So If I have a tag for "finance" the color could be could be #0000ff and tag for "medical" could have a color value of #00ff00 etc. 
Would this be possible using this package? 

I have created a migration to extend the DB fields to add a color field, but where to I keep my custom tag model and how do I reference it in my other models. 

I would appreciate it if you can point me in the right direction!

**Comment by freekmurze** [comment]
Hi,

you've already done a lot of right steps. If you just want to add a field, you can just use the provided `Tag` model. If you've already migrated your db, you can just do:

```php
$tag = new \Spatie\Tags\Tag:: findOrCreate('yourTag');
$tag->color = '#00ff00';
$tag->save();
```

**Comment by devchops** [comment]
Hi @freekmurze,

Firstly, Thanks for the quick response and thank you for pointing me in the right direction. 

After using the example you provided:

```
      $tag = new Tag;
      $tag->findOrCreate('Finance');
      $tag->color = '#00ff00';
      $tag->save();
```

When the above is executed, the new "Finance" tag created is saved to the DB, but without the color field. After the finance tag is saved, it tries to save another empty tag with only the color info (and name=NULL, slug=NULL) - which fails as shown below:

> SQLSTATE[23502]: Not null violation: 7 ERROR: null value in column "name" violates not-null constraint
> DETAIL: Failing row contains (32, null, null, null, 16, 2016-11-10 06:50:08, 2016-11-10 06:50:08, #00ff00). (SQL: insert into "tags" ("color", "order_column", "updated_at", "created_at") values (#00ff00, 16, 2016-11-10 06:50:08, 2016-11-10 06:50:08) returning "id")
> 

However, after playing around, I tried the following does save both the tag and color field together:

```
      $tag = new Tag;
      $tag->name = ['en'=>'finance'];
      $tag->color = '#00ff00';
      $tag->save();
      $project->attachTag($tag);

```

Unfortunately, this does not use the `findOrCreate` method, so it keeps adding to the tags table. 

How can I implement this using the `findOrCreate` method - as you have illustrated in the example above instead of creating a new one every time?

Also, FYI - I am using Postgres. The package seems to work fine, except for the issue mentioned above.

**Comment by freekmurze** [comment]
Try replacing this:

```php
$tag = new Tag;
$tag->findOrCreate('Finance');
$tag->color = '#00ff00';
$tag->save();
```

by this:

```php
Tag = Tag::findOrCreate('Finance');
$tag->color = '#00ff00';
$tag->save();
```

**Comment by devchops** [comment]
That worked!!

Thank you Sir - very helpful indeed! I need to go post-card shopping now 👍
