### ISSUE TITLE
Allow to rename order_column

### ISSUE THREAD

**Issue by jonagoldman** [spatie/laravel-tags#192]
Use
```php
->orderBy($this->sortable['order_column_name'])
```
instead of
```php
->orderBy('order_column')
```

so it is possible to extend Tag model and override the properties:

```php
use Spatie\Tags\Tag as SpatieTag;

class Tag extends SpatieTag
{
    public $sortable = [
        'order_column_name' => 'order',
        'sort_when_creating' => true,
    ];
}
```

**Comment by freekmurze** [comment]
Feel free to PR this with ample tests.

**Comment by jonagoldman** [comment]
@freekmurze honestly, spatie/eloquent-sortable already ships with a `ordered()` scope, why not to use it?
The only change needed is to use:

```php
->ordered();
``` 

instead of:

```php
->orderBy('order_column');
```

**Why this works?**
Because the [order scope](https://github.com/spatie/eloquent-sortable/blob/master/src/SortableTrait.php#L33-L36) in the sortable package already takes cares of checking for the column name in the database.

**What about tests?**
I have run the tests manually changing the column name in the migration stub, but I don't really know the best way to change the column while running the tests.

I can PR with everything but the column name change in the tests...

**Comment by freekmurze** [comment]
Create the PR and I'll decide then if we're going to merge it in.
