### ISSUE TITLE
Delete Tag in Database When Removed from Post

### ISSUE THREAD

**Issue by studiorooster** [spatie/laravel-tags#194]
I just started to use this package in my Laravel 5.8 project and inside Nova dashboard.  It works great, but I was wondering if there is a way to remove the associated tag entry from the tags table if removed from my Post model entry?  Thank you.

**Comment by freekmurze** [comment]
That's something out of scope for this package. You need to handle tag deletion yourself. Maybe you could listen for the deletion event of Post, take a look at which tags it had, verify if they're not used on other post models and if not, delete those tags.
