### ISSUE TITLE
Allow to display a link to the Tag resource

### ISSUE THREAD

**Issue by fkeloks** [spatie/laravel-tags#196]
Hello,

I would like to have the possibility to have a link to the resource Nova of the tag.

I tried to change the formatting as well:
```php
Tags::make('Tags')
    ->doNotLimitSuggestions()
    ->displayUsing(function ($tags) {
        return $tags->map(function ($tag) {
            return '<a href="' . Nova::path() . '/resources/tags/' . $tag->id . '">' . $tag->name . '</a>';
        })->values();
    }),
```

But I quickly realized that the view did not allow it:

`vendor/spatie/nova-tags-field/resources/js/components/Nova/DetailField.vue` :
```html
<p slot="value" v-text="field.value.join(', ')"></p>
```

Is it possible to implement a feature that displays a link to the tag instead of displaying its name?

Thank you for your work !

**Comment by freekmurze** [comment]
If this is can be added in a simple way, feel free to submit a PR that adds this to the package.

**Comment by fkeloks** [comment]
PR created here https://github.com/spatie/nova-tags-field/pull/49
