### ISSUE TITLE
"Relations" tab of Laravel Nova with this tag system

### ISSUE THREAD

**Issue by fkeloks** [spatie/laravel-tags#197]
Hello,

How can I take advantage of the "Relations" tab of Laravel Nova with this tag system?

For example, this code allows me to have the list of sites for the current server:

`App\Models\Server.php`:
```php
public function websites() {
    return $this->hasMany(Website::class, 'server_id', 'id');
}
```

`Nova\Server.php`:
```php
RelationshipCount::make('Sites', 'websites'),
HasMany::make('Sites', 'websites', 'App\\Nova\\Website'),
```

Thank you for your work !
Florian

**Comment by freekmurze** [comment]
I don't have time to spend time on this now. If you find a good solution, I'd appreciate you posting it here for other users of the package.

**Comment by fkeloks** [comment]
Hello,

I finally found the solution.
You have to use your own Tag class, and add the relationship with the target as a morphedByMany relationship.

Example:
```php
<?php

namespace App\Models;

use Illuminate\Support\Facades\DB;
use Spatie\Tags\Tag as SpacieTag;

class Tag extends SpacieTag {

    protected $with = ['documents'];

    public function documents() {
        return $this->morphedByMany(Document::class, 'taggable', 'taggables');
    }

}
```
