### ISSUE TITLE
Search Tag by containing

### ISSUE THREAD

**Issue by MjeTjeu** [spatie/laravel-tags#204]
Hello dear people,

If the Tag has a Type , this

         $tag = Tag::containing($request->name)->get();

is not working?
If Type = NULL it works fine .

**Comment by freekmurze** [comment]
This test proves that the scope is working as intended:

https://github.com/spatie/laravel-tags/blob/master/tests/TagTest.php#L85-L99

Could you PR a failing test for me to look at?
