### ISSUE TITLE
Error on creating tag

### ISSUE THREAD

**Issue by gizburdt** [spatie/laravel-tags#21]
Hi,

I'm trying to create a tag with this code: `Tag::create(['name' => 'my tag'])`.

But when I tun the code I get this error: `Type error: Return value of Spatie\Tags\Tag::getTranslations() must be of the type array, string returned`. I'm using tinker to quickly create a tag.

**Comment by freekmurze** [comment]
That `name` field is translatable. Try this, assuming your locale is set to `en`.

```php
NewsItem::create([
   'name' => [
      'en' => 'my tag',
   ],
]);
```

**Comment by gizburdt** [comment]
Thanks :)

**Comment by ferrarafer** [comment]
https://github.com/spatie/laravel-tags/issues/21#issuecomment-262076084

Actually

`Tag::create([
   'name' => [
      'en' => 'my tag',
   ],
]);`
