### ISSUE TITLE
Reconsider making tags searchable?

### ISSUE THREAD

**Issue by orrd** [spatie/laravel-tags#215]
There is an issue #45 from two years ago asking for tags to be searchable by slug.  This is a very common use case (note that there are 17 thumbs-up and positive reactions on the work-around solution that issue).  I'm not actually sure why slugs exist if we don't have the ability to search by them.  

This is a common use case and a highly requested feature.  Maybe consider adding it so people no longer have to extend the class to use this functionality?

If you would like I can submit a pull request of the code to add that feature.

**Comment by orrd** [comment]
For others who are looking for a solution for this, I reviewed all of the forks of this package and found https://github.com/zaengle/laravel-tags which looks like it does have one solution that lets you use the withAllTags() or withAnyTags() scopes with a second parameter that can be set to 'slug' to search the slugs.  It's forked from an older version and may not be an ideal solution, but may work.

**Comment by freekmurze** [comment]
Feel free to submit a PR for this (make sure to add tests and updated docs), and I’ll consider merging it 👍
