### ISSUE TITLE
create tags and set slug

### ISSUE THREAD

**Issue by Mahdi-Ba** [spatie/laravel-tags#224]
I'd like to set special slug in laravel-tags V2 what is best solution 
Now I am overriding trait HasSlug like this 

```
 protected function generateSlug(string $locale): string
    {
        if($this->getTranslation('slug', $locale))
        {

            return  $this->getTranslation('slug', $locale);
        }
        else
        {
            $slugger = config('tags.slugger');
            $slugger = $slugger ?: '\Illuminate\Support\Str::slug';
            return call_user_func($slugger, $this->getTranslation('name', $locale));
        }
    }

==================     for create use this      =======================
   $tag = Tag::create([
            'name' => $faker->text($maxNbChars = 6),
            'slug' => ["fa" =>"سلام"]

        ]);
        $tag = Tag::create([
            'name' => $faker->text($maxNbChars = 6),
        ]);
        $tag->slug = ["fa"=>'  مهدی'];
        $tag->save();
```

**Comment by Mahdi-Ba** [comment]
this Package don't have any focus to set slug ??!!!

**Comment by KFTco** [comment]
@Mahdi-Ba
Dear Mahdi
There is a solid solution for Persains slugs which helps you to generate slug in Persian properly 
First making a Helper Class as following
`    public static function persian_slug( $string, $separator = '-' ) {
        $_transliteration = array(
            '/ä|æ|ǽ/'                         => 'ae',
            '/ö|œ/'                           => 'oe',
            '/ü/'                             => 'ue',
            '/Ä/'                             => 'Ae',
            '/Ü/'                             => 'Ue',
            '/Ö/'                             => 'Oe',
            '/À|Á|Â|Ã|Å|Ǻ|Ā|Ă|Ą|Ǎ/'           => 'A',
            '/à|á|â|ã|å|ǻ|ā|ă|ą|ǎ|ª/'         => 'a',
            '/Ç|Ć|Ĉ|Ċ|Č/'                     => 'C',
            '/ç|ć|ĉ|ċ|č/'                     => 'c',
            '/Ð|Ď|Đ/'                         => 'D',
            '/ð|ď|đ/'                         => 'd',
            '/È|É|Ê|Ë|Ē|Ĕ|Ė|Ę|Ě/'             => 'E',
            '/è|é|ê|ë|ē|ĕ|ė|ę|ě/'             => 'e',
            '/Ĝ|Ğ|Ġ|Ģ/'                       => 'G',
            '/ĝ|ğ|ġ|ģ/'                       => 'g',
            '/Ĥ|Ħ/'                           => 'H',
            '/ĥ|ħ/'                           => 'h',
            '/Ì|Í|Î|Ï|Ĩ|Ī|Ĭ|Ǐ|Į|İ/'           => 'I',
            '/ì|í|î|ï|ĩ|ī|ĭ|ǐ|į|ı/'           => 'i',
            '/Ĵ/'                             => 'J',
            '/ĵ/'                             => 'j',
            '/Ķ/'                             => 'K',
            '/ķ/'                             => 'k',
            '/Ĺ|Ļ|Ľ|Ŀ|Ł/'                     => 'L',
            '/ĺ|ļ|ľ|ŀ|ł/'                     => 'l',
            '/Ñ|Ń|Ņ|Ň/'                       => 'N',
            '/ñ|ń|ņ|ň|ŉ/'                     => 'n',
            '/Ò|Ó|Ô|Õ|Ō|Ŏ|Ǒ|Ő|Ơ|Ø|Ǿ/'         => 'O',
            '/ò|ó|ô|õ|ō|ŏ|ǒ|ő|ơ|ø|ǿ|º/'       => 'o',
            '/Ŕ|Ŗ|Ř/'                         => 'R',
            '/ŕ|ŗ|ř/'                         => 'r',
            '/Ś|Ŝ|Ş|Ș|Š/'                     => 'S',
            '/ś|ŝ|ş|ș|š|ſ/'                   => 's',
            '/Ţ|Ț|Ť|Ŧ/'                       => 'T',
            '/ţ|ț|ť|ŧ/'                       => 't',
            '/Ù|Ú|Û|Ũ|Ū|Ŭ|Ů|Ű|Ų|Ư|Ǔ|Ǖ|Ǘ|Ǚ|Ǜ/' => 'U',
            '/ù|ú|û|ũ|ū|ŭ|ů|ű|ų|ư|ǔ|ǖ|ǘ|ǚ|ǜ/' => 'u',
            '/Ý|Ÿ|Ŷ/'                         => 'Y',
            '/ý|ÿ|ŷ/'                         => 'y',
            '/Ŵ/'                             => 'W',
            '/ŵ/'                             => 'w',
            '/Ź|Ż|Ž/'                         => 'Z',
            '/ź|ż|ž/'                         => 'z',
            '/Æ|Ǽ/'                           => 'AE',
            '/ß/'                             => 'ss',
            '/Ĳ/'                             => 'IJ',
            '/ĳ/'                             => 'ij',
            '/Œ/'                             => 'OE',
            '/ƒ/'                             => 'f'
        );


        $quotedReplacement = preg_quote( $separator, '/' );

        $merge = array(
            '/[^\s\p{Zs}\p{Ll}\p{Lm}\p{Lo}\p{Lt}\p{Lu}\p{Nd}]/mu'                => ' ',
            '/[\s\p{Zs}]+/mu'                                                    => $separator,
            sprintf( '/^[%s]+|[%s]+$/', $quotedReplacement, $quotedReplacement ) => '',
        );

        $map = $_transliteration + $merge;
        unset( $_transliteration );

        return mb_strtolower( preg_replace( array_keys( $map ), array_values( $map ), $string ) );
    }
`
Then you can use this function as a callBack in  configs of libraries that it needs to be compatible with Persian  :
Here is example of this library setting :
`return [

    /*
     * The given function generates a URL friendly "slug" from the tag name property before saving it.
     * Defaults to Str::slug (https://laravel.com/docs/5.8/helpers#method-str-slug)
     */
    'slugger' => [\App\Helper\Helper::class,'persian_slug'],
];`
