### ISSUE TITLE
Handle validation

### ISSUE THREAD

**Issue by zefexdeveloper** [spatie/laravel-tags#226]
I'm using the tags with multiple types, imagine the situation where I have a form so the user can select some predefined tags (I have a seed that I defined a few `services` type tags) and I'm listing all of them so the user can select the ones he wants.
The problem is that: how can I make sure that the selected (or sent as POST) tags are actually from `service` type? I can't just rely on `syncTagsWithType` because it uses `findOrCreate` meaning that if the user adds manually using the inspector (for instance) another tag and send as POST it will be added to the database.
I was wondering, is there a way for me to validate based on the type?

**Comment by zefexdeveloper** [comment]
bump

**Comment by Chris1904** [comment]
Sorry, not too familiar and was just trying to understand your issue; can you not do some server-side validation to check for this?

**Comment by zefexdeveloper** [comment]
In order to make this clearer: I have a few tags with a type `services`, I want to validate the array and make sure it exists on the database using that type.

I tried like that but with no success:

```php
Rule::exists('tags,slug')->where(function ($query) {
    $query->where('type', 'service');
})
```

**Comment by mikelucid** [comment]
in case anyone stumbles upon this. Found a solution: https://github.com/codezero-be/laravel-unique-translation

public function rules(): array
{
    return [
        'name' => 'required|unique_translation:tags',
    ];
}
