### ISSUE TITLE
Adding an order to tags

### ISSUE THREAD

**Issue by Sylk** [spatie/laravel-tags#238]
I'm wanting to keep track of the order of my items that have tags that I have, so that I can sort items with tags.

I'm currently working on my own fix, but is there a recommended way to do something such as this?

**Comment by freekmurze** [comment]
The `tags` table already has an `order_column`.

**Comment by Sylk** [comment]
So are you saying that I can implement the `order_column` on the `taggables`  table and that I should be able to sort what order the items are in my tags?

I think I'm trying to abuse this package and use it for things it wasn't entirely intended for.
