### ISSUE TITLE
Is MariaDB supported now?

### ISSUE THREAD

**Issue by Fossil01** [spatie/laravel-tags#239]
I looked at old issues but couldn't find a definitive answer. Is MariaDB supported now in this package?

I'm running MariaDB 10.4.10

**Comment by freekmurze** [comment]
If MariaDB supports the same JSON function as MySQL then the answer is yes.

**Comment by Fossil01** [comment]
It doesn't, but I found numerous issues/PR's with possible changes to support both. What's the reason these are ignored?

**Comment by JJCLane** [comment]
I'm facing an issue with MariaDB json types and collations. The query works if you manually specify the collation e.g. 

`select * from `tags` where JSON_UNQUOTE(
    JSON_EXTRACT('name', '$."en"')
) collate utf8_unicode_ci like '%fish%' `

**Comment by Kokil** [comment]
i am facing the same.
