### ISSUE TITLE
disable translation for slugs

### ISSUE THREAD

**Issue by zefexdeveloper** [spatie/laravel-tags#240]
Is it possible to remove translation for slugs?

**Comment by freekmurze** [comment]
There’s too little info to go on.

**Comment by zefexdeveloper** [comment]
> There’s too little info to go on.

Sorry I miss clicked and pressed the enter key before actually typing the question.

I wanted to disable translation for slugs and leave it only for the name.

**Comment by jeffsmor** [comment]
Hi everyone, take a look at my solution...

`trait HasSpatieTag
{
    public static function bootHasSlug()
    {
        static::saving(function (Model $model) {
            $model->slug = $model->generateSlug('en');
        });
    }

    public static function findFromString(string $name, string $type = null, string $locale = null)
    {
        $locale = $locale ?? static::getLocale();

        return static::query()
            ->where('type', $type)
            ->where(function ($query) use ($name, $locale) {
                $query->where("name->{$locale}", $name)
                    ->orWhere("slug", $name);
            })
            ->first();
    }

    public static function findFromStringOfAnyType(string $name, string $locale = null)
    {
        $locale = $locale ?? static::getLocale();

        return static::query()
            ->where("name->{$locale}", $name)
            ->orWhere("slug", $name)
            ->get();
    }
}`
