### ISSUE TITLE
Duplicated tags

### ISSUE THREAD

**Issue by chadidi** [spatie/laravel-tags#244]
Example below:

```
1. attach: ElasticSearch
2. attach: Elasticsearch
3. attach: elasticsearch
```
This will create 3 tags even though they are the same!!

**Comment by chadidi** [comment]
I found out why this happened, the package 📦 is using the name when checking for a tag existent, I think 🤔 the tag name is not unique instead the slug should be used.

**Comment by freekmurze** [comment]
I think it's good default behaviour for the package. If you want these three tags being treated the same, convert them to the same string before adding it as a tag.

**Comment by chadidi** [comment]
Hey @freekmurze, I have created a pull request for a possible alternative solution!
I hope it can be merged, as I believe it can be useful for some people out there.
thanks
