### ISSUE TITLE
Request - support for multi tenancy

### ISSUE THREAD

**Issue by kutubjt** [spatie/laravel-tags#246]
This is a request and not an issue. Would be good to have support for multi-tenancy, where we can set the tenant for each tag being created, this will allow each tenant to have their own tags.

**Comment by freekmurze** [comment]
Thank you for this proposal 

We don't need this ourselves, so we're not going to add it to the package.

**Comment by kutubjt** [comment]
Thanks for your prompt response and I understand.
Any recommendation on how should I go about doing this customization specific to my project?

**Comment by freekmurze** [comment]
Feel free to fork our code and make the necessary modifications in your fork.
