### ISSUE TITLE
SQL Syntax Error -> json_unquote does not exist

### ISSUE THREAD

**Issue by OneGerman** [spatie/laravel-tags#248]
I've uploaded my whole project today on my domain. I get this error:

`SQLSTATE[42000]: Syntax error or access violation: 1305 FUNCTION laravel_app.json_unquote does not exist (SQL: select * from `tags` where json_unquote(json_extract(`name`, '$."de"')) = Gaming and `type` is null limit 1)`

My Controller looks like that: [https://pastebin.com/RA5gi0Qk](https://pastebin.com/RA5gi0Qk)

**Comment by freekmurze** [comment]
Make sure you use MySQL (or a database that has those json functions available.

**Comment by AjithLalps** [comment]
Have the same issue. Since we are hosting our website on shared hosting, the supported MySQL version is 5.7 and it doesn't have the support for `json_unquote()` function.
