### ISSUE TITLE
L 5.6 failed !

### ISSUE THREAD

**Issue by AEK-BKF** [spatie/laravel-tags#249]
Hi,
I'm trying to install it on L5.6, I get this error :

> Your requirements could not be resolved to an installable set of packages.
> 
>   Problem 1
>     - The requested package spatie/laravel-translatable (locked at 2.2.1, required as ^4.2) is satisfiable by spatie/laravel-translatable[2.2.1] but these conflict with your requirements or minimum-stability.
>   Problem 2
>     - Conclusion: remove laravel/framework v5.6.39
>     - Conclusion: don't install laravel/framework v5.6.39
>     - spatie/laravel-tags 2.5.0 requires laravel/framework ~5.8|^6.0 -> satisfiable by laravel/framework[5.8.x-dev, 6.x-dev].
>     - spatie/laravel-tags 2.5.1 requires laravel/framework ~5.8|^6.0 -> satisfiable by laravel/framework[5.8.x-dev, 6.x-dev].
>     - spatie/laravel-tags 2.5.2 requires laravel/framework ~5.8|^6.0 -> satisfiable by laravel/framework[5.8.x-dev, 6.x-dev].
>     - spatie/laravel-tags 2.5.3 requires laravel/framework ~5.8|^6.0 -> satisfiable by laravel/framework[5.8.x-dev, 6.x-dev].
>     - Can only install one of: laravel/framework[5.8.x-dev, v5.6.39].
>     - Can only install one of: laravel/framework[6.x-dev, v5.6.39].
>     - Installation request for laravel/framework (locked at v5.6.39, required as 5.6.*) -> satisfiable by laravel/framework[v5.6.39].
>     - Installation request for spatie/laravel-tags ^2.5 -> satisfiable by spatie/laravel-tags[2.5.0, 2.5.1, 2.5.2, 2.5.3].

Is there any release for L5.6 ?

Thanks

**Comment by smartbos** [comment]
I'm not sure but packagist says you might use 2.1.5 for L5.6.

**Comment by AEK-BKF** [comment]
It's ok, it was my mistake ^^' I've already installed it without any error
Thanks.

**Comment by mmubasharsheikh** [comment]
> It's ok, it was my mistake ^^' I've already installed it without any error
> Thanks.

What was the mistake?
