### ISSUE TITLE
using your own tag model

### ISSUE THREAD

**Issue by vesper8** [spatie/laravel-tags#25]
Hi there,

Boy I feel kinda stupid for asking this.. specially since there's already two other issues opened regarding extending the tag model and using your own.

So I have my own Tag model to which I want to add all the functionality of your tag model. So that model extends Spatie\Tags\Tag

All good so far

Then, you say "All you need to do is override the getTagClassName method from the HasTags trait."

Sounds simple enough. My question is, since I don't want to edit a vendor file. Does that mean I should create my own trait, so I can extend it with Spatie\Tags\HasTags, and in that trait I should override the 

```
    public static function getTagClassName(): string
    {
        return Tag::class;
    }
```

method and have it return my custom tag model that extends Spatie\Tags\Tag ?

That's what I would do.. but was wondering if there was another way of overriding the getTagClassName method of the HasTags trait without creating a trait of my own.

Guess I just haven't done a lot of overriding like this in the past.

Thanks!

**Comment by vesper8** [comment]
I'd like to add that.. I have no problem at all with your tag model. The only reason I want to use my own tag model is because I use a multi-connection (multi-database) setup and my tag model is not in the default connection. If there was a way to specify which connection/table your tag model uses without editing vendor files then I would have done that instead.

**Comment by freekmurze** [comment]
> Boy I feel kinda stupid for asking this.. specially since there's already two other issues opened regarding extending the tag model and using your own.

No problem, I glad that you asked this question as my answer will hopefully help you and future users of the package.

Fortunately to specify the tag model no vender file needs to be edited. You just need to  add the `getTagClassName` to you own model to which you want to add taggable behaviour.

So if you have let's say a `NewsItem` model in your project you'll need to do this:


```php
use Illuminate\Database\Eloquent\Model;

class NewsItem extends Model
{
   public static function getTagClassName(): string
   {
       return YourTagModel::class;
   }
}
```

Does this solve your issue?

**Comment by vesper8** [comment]
Ahhh! So any model that uses a trait can override that method's trait the same way it would override an extended class' ?

But to be clear.. it would look like this right?

```
use Illuminate\Database\Eloquent\Model;

class NewsItem extends Model
{
   use HasTags;

   public static function getTagClassName(): string
   {
       return MyTag::class;
   }
}
```
```
use Illuminate\Database\Eloquent\Model;

class MyTag extends Model extends Spatie\Tags\Tag
{

}
```

So traits are basically just another way of extending a class multiple times?

If so then yes that solves my problem! Thanks!

**Comment by freekmurze** [comment]
Correct, that looks right.

> So traits are basically just another way of extending a class multiple times?

Yup, a class will gain all functions from it's traits.

**Comment by jtomek** [comment]
I think it would be a good idea to incldue a new chapter called customization/extensions to the documentation.
