### ISSUE TITLE
NOT NULL constraint failed: tags.slug

### ISSUE THREAD

**Issue by brandc87** [spatie/laravel-tags#250]
Not sure if this is an issue my end but when trying to attach tags using:

`$post = factory(Post::class)->create()->attachTags(['tag', 'another-tag']);`

or

`$post = factory(Post::class)->create();` 
`$post->attachTags(['tag', 'another-tag']);`

It results in the following error inside my Unit tests:

`Integrity constraint violation: 19 NOT NULL constraint failed: tags.slug (SQL: insert into "tags" ("name", "type", "updated_at", "created_at") values ({"en":"tweet"}, ?, 2020-01-15 22:04:00, 2020-01-15 22:04:00))`

Using the following method works fine:

`$post = factory(Post::class)->create(['tags' => ['tag 1', "tag 2"]]);`

PHP 7.4 Laravel 6.2

**Comment by freekmurze** [comment]
I'm thinking this is caused by certain eloquent events not firing when using a factory. The easy way out for you would be to drop the `NOT NULL` constraint on `slug`. Just remove that from your migration.
