### ISSUE TITLE
Get all the tag of any model

### ISSUE THREAD

**Issue by hemratna** [spatie/laravel-tags#252]
Is there any way I can get all the tag of any particular model?

For example, I have a model `News`, then `$news->tags()` or similar, where I can get all the tag associated with that modal.

#sillyQuestion But not able to figure out from the doc. 😢

**Comment by freekmurze** [comment]
Try `$news->tags`

**Comment by swim89** [comment]
Sorry for writing on this old post, but I would to do the same thing.
I used this code but I had empty result.
`$documents = new Document();
 $allTags = $document->tags`

I would get all tags of model "Document" without filtering for a specific record.

**Comment by uyab** [comment]
For anyone interested: https://github.com/spatie/laravel-tags/discussions/415#discussioncomment-9565959
