### ISSUE TITLE
Retrive all tags from model but filtered by type  `$model->tags`.

### ISSUE THREAD

**Issue by Webpills** [spatie/laravel-tags#253]
That easy, you can do that with `$model->tags`.

_Originally posted by @freekmurze in https://github.com/spatie/laravel-tags/issues/119#issuecomment-411829768_

Hi is possible to use this with types?

like this $model->tags('type1')  for retrive onlie on type?
thanks

**Comment by Houbsi** [comment]
Hi @Webpills 

> From your model object, you can also get all tags with a specific type via the tagsWithType method:
> `$newsItem->tagsWithType('firstType');  // returns a collection`

This can you find here at the bottom of the page: https://docs.spatie.be/laravel-tags/v2/advanced-usage/using-types/
