### ISSUE TITLE
Exclude tags

### ISSUE THREAD

**Issue by KuroUsagi1010** [spatie/laravel-tags#262]
when retrieving tags we use Withalltags and Withanytags. 

Is there any way I can edit things and create a follow up for exclude tags? like Use Withanytags but exclude these models containing tags['sample', 'sample'] .

**Comment by 1stevengrant** [comment]
@KuroUsagi1010 did you get a resolution for this?

**Comment by gbrits** [comment]
I was also interested if @freekmurze had a solution for querying `->excludingAnyTags(['sport'])` for example? (PS. Thnx for another great package)
