### ISSUE TITLE
How to have multiple tag sets per model?

### ISSUE THREAD

**Issue by Synchro** [spatie/laravel-tags#266]
It's quite straightforward to have a single set of tags associated with a model - but I need to have multiple sets of tags for a single model. For example, I have an image library that has a set of tags that have been generated by a machine learning system, and another set that has been manually curated, and i need to keep them separate. Is there any way to handle multiple tag sets using this package?

**Comment by freekmurze** [comment]
Take a look at tag types: https://docs.spatie.be/laravel-tags/v2/advanced-usage/using-types/

**Comment by Synchro** [comment]
Perfect, thanks!
