### ISSUE TITLE
slugger give call_user_func() expects parameter 1 to be a valid callback, no array or string given

### ISSUE THREAD

**Issue by tkart38** [spatie/laravel-tags#268]
hi
i'm setting the slugger config to "true" but give this error :
call_user_func() expects parameter 1 to be a valid callback, no array or string given

any advices?
thanks

**Comment by connor11528** [comment]
It looks like this was a breaking change with a version bump. We used to pass in the tag object to the `attachTags` method but now it accepts a string as the first param.
