### ISSUE TITLE
Your requirements could not be resolved to an installable set of packages.

### ISSUE THREAD

**Issue by techguydev** [spatie/laravel-tags#269]
Problem 1
    - Installation request for spatie/nova-tags-field ^3.0 -> satisfiable by spatie/nova-tags-field[3.0.0].
    - spatie/nova-tags-field 3.0.0 requires laravel/nova ^3.0 -> no matching package found.

Potential causes:
 - A typo in the package name
 - The package is not available in a stable-enough version according to your minimum-stability setting
   see <https://getcomposer.org/doc/04-schema.md#minimum-stability> for more details.
 - It's a private package and you forgot to add a custom repository to find it

**Comment by riasvdv** [comment]
You're trying to install our nova-tags-field and composer can't find the laravel/nova installation, please refer to their docs on how to install laravel nova with composer
