### ISSUE TITLE
Syncing tags

### ISSUE THREAD

**Issue by seanhudson** [spatie/laravel-tags#27]
So I have quite a few tags that I created like this.

`$tag = Tag::findOrCreate($request->name, $request->type);`

For example:

`$request->name = 'web development';`
`$request->type = 'primary';`

The tag gets created. That seems to work fine. Woohoo.
Then, on another page, I tried to attach a model to the tag. I would do this:

`$company->syncTags($all_tags);`

If "web development" was one of the tags in the $all_tags array, it doesn't get recognized. Instead, another _new_ tag gets created with the exact same name and slug except it has an empty type.

Why does it ignore the tag that already exists?

**Comment by freekmurze** [comment]
If you pass a tag as a string an empty type is assumed.

You'll find that if you pass a typed tag as `Tag` instance to `syncTags` the existing tag won't be recreated with an empty type.

```php
$company->syncTags(['web development']); // tag will be created with an empty type

$tag = Tag::findOrCreate('web development', 'primary');

$company->syncTags([$tag]); // no new tag will be created
```
