### ISSUE TITLE
Selecting items tagged with tagsWithType

### ISSUE THREAD

**Issue by barjas** [spatie/laravel-tags#28]
```
$tag = Tag::findOrCreate('gossip', 'newsTag');
$tag2 = Tag::findOrCreate('headline', 'newsTag');
NewsItem::withAnyTags([$tag, $tag2])->get();
```

the above code return NewsItem **empty**

**Comment by sebastiandedeyne** [comment]
How are you attaching the tags to the news item?

**Comment by barjas** [comment]
I'm following the documentation exactly.

Am in laravel 5.4

**Comment by freekmurze** [comment]
You can make it easier for us if you provide us with the specific code to reproduce the problem.

Could you please post the actual code you're using to attach the tags?

The tests also contain [various examples](https://github.com/spatie/laravel-tags/blob/master/tests/HasTagsTest.php) on how the package can be used.

**Comment by barjas** [comment]
i did the following steps:

1. installed the package following the installation instruction on  https://github.com/spatie/laravel-tags

2. i have a model called "Project" so i edit it as per the instruction: 
`
...
class Project extends Model
{
	use \Spatie\Tags\HasTags;`
...

3. my controller: 
`
...
use Spatie\Tags\Tag;
class MainController extends Controller
{
    public function __construct()
    {
    }
	public function test()
	{
		$tagWithType = Tag::findOrCreate('headline', 'newsTag');
		$Project = Project::find(2785);
		$Project->attachTag($tagWithType);
		$result = Project::withAnyTags([$tagWithType])->get();
		dd($result);
	}
`
result is empty. 

also i noticed that every time i run the function, the "taggable" database table add another duplicated  row with the 
tag_id     |     taggable_id     |     taggable_type
----------------------------------------------------------------
1	       |    2785                 |    App\\Models\\Project
1	       |    2785                 |    App\\Models\\Project
1	       |    2785                 |    App\\Models\\Project
1	       |    2785                 |    App\\Models\\Project

the "attachTag" function attach the same tage to the same "project" every time.

**Comment by sebastiandedeyne** [comment]
There appear to be some issues with `withAnyTags` and tag types, we're investigating!

It might work for now by explicitly providing a `$tagType`.

```php
$result = Project::withAnyTags([$tagWithType], 'newsTag')->get();
```

**Comment by barjas** [comment]
What about the duplicated entries in the taggble table? Is that how it was intended to be?

**Comment by freekmurze** [comment]
@AlexVanderbist can you take a look at that duplicated entries problem?

**Comment by AlexVanderbist** [comment]
The issue with the duplicate `taggable` entries is fixed in #33.

**Comment by vool** [comment]
Just wondering if there was any solution to the issue ?    

Model::withAnyTags([$tagWithType])->get();

I have also tried the suggestion by @sebastiandedeyne above and this does seem to work either 

$result = Model::withAnyTags([$tagWithType], 'type')->get();

**Comment by AlexVanderbist** [comment]
Hi @vool 

I tried your example code on Laravel 5.4 (PHP 7.1) with the latest version of this package and it seems to work.

I used the following code:

```php
Project::create(['name' => 'Test project without tag']);

$project = Project::create(['name' => 'Test project']);
$tagWithType = Tag::findOrCreate('headline', 'newsTag');
$project->attachTag($tagWithType);

$result = Project::withAnyTags([$tagWithType])->get();

dump($result);
// Result contains a Collection of Projects, in this case just one "Test project"
```

If you still run into any issues, let me know!

**Comment by fregoem** [comment]
Hi @AlexVanderbist 

In the example above, you search for projects with a tag AND type.

I must be able to search for projects with only a specific tag. 

If I use $result = Project::withAnyTags('headline')->get() , it returns nothing. 

If I use $result = Project::withAnyTags('headline','newsTag')->get(), it returns the items.

Can you help me with this?

**Comment by AlexVanderbist** [comment]
Hi @fregoem 

I haven't looked into this too much but you could try `Project::tagsWithType('headline')`.

If this is still a problem feel free to open a new issue on this repo.

**Comment by fregoem** [comment]
Hi @AlexVanderbist Doesn't tagsWithType search for models with a tag type?
I want to search for models with just a tag. Does the method tagsWithTag exist?

**Comment by AlexVanderbist** [comment]
You're right, totally mixing things up here, sorry about that 😅

Can you try passing an array to with any tags like this? 
`Project::withAnyTags(['headline])`

**Comment by fregoem** [comment]
I already tried this but it doesn't work.
