### ISSUE TITLE
Searching Tags using Spatie/laravel-searchable

### ISSUE THREAD

**Issue by wecojo** [spatie/laravel-tags#281]
Is it possible to search tags from the database using spatie/laravel-searchable and display it in table form? If can, how can I do it?

**Something LIke this: **
`$results = (new search())
->registerModel('\Spatie\Tags\Tag::class, ['name'])
->search($request->input('query'));`

Thanks.

**Comment by freekmurze** [comment]
This package has no opinion on how tags should be searched. 

We can't assist you with project specific questions.

**Comment by muarachmann** [comment]
> Is it possible to search tags from the database using spatie/laravel-searchable and display it in table form? If can, how can I do it?
> 
> **Something LIke this: **
> `$results = (new search()) ->registerModel('\Spatie\Tags\Tag::class, ['name']) ->search($request->input('query'));`
> 
> Thanks.

You can use the `Tag::containing($query)->get()` to get it done, if you insist on Searchable then consider creating your own model and implementing it https://spatie.be/docs/laravel-tags/v2/advanced-usage/using-your-own-tag-model
