### ISSUE TITLE
syntax error, unexpected 'array'

### ISSUE THREAD

**Issue by dcblogdev** [spatie/laravel-tags#284]
I've just installed this package and added the trait to my model, then when the model. is loaded I'm getting:

>syntax error, unexpected 'array' (T_ARRAY), expecting function (T_FUNCTION) or const (T_CONST)

Which related to:

```php
 protected array $queuedTags = [];
```

https://flareapp.io/share/87nOKoG5#F56

I'm running PHP 7.4.10

Have I missed a step on installation?

**Comment by freekmurze** [comment]
You're not fully on PHP 7.4

https://freek.dev/1598-how-to-check-which-version-of-php-you-are-running

**Comment by daniberv** [comment]
Have the same problem
Laravel 8.0
PHP 7.4.11
spatie/laravel-tags 3.0
[https://prnt.sc/v8g85y](url)

**Comment by dcblogdev** [comment]
In my case, my terminal was 7.4 but my valet was using 7.3. I then told valet to use 7.4 specifically:

```php
valet use php@7.4
```
