### ISSUE TITLE
Create v4.x (PHP8+)

### ISSUE THREAD

**Issue by patinthehat** [spatie/laravel-tags#302]
Per [request](https://twitter.com/freekmurze/status/1367405006421393408), I plan on creating a new major version supporting only PHP 8+ _(v4.x)_.

@freekmurze, beyond the PHP version constraint and making sure tests are passing, is there anything additional that should be done for the PR?  I'm not clear on whether or not you're looking for the code to be converted to use PHP 8 features or just wanted to start with the version constraint.

Thanks!

**Comment by freekmurze** [comment]
I don't need any additional features for now. I'm looking for the most clear code at this point. If possible you may simplify things (and even drop features) if that would make the code more readable. Feel free to drop support for all non-current Laravel versions too 👍

**Comment by patinthehat** [comment]
Do you prefer that it implements `spatie/laravel-package-tools`?

**Comment by freekmurze** [comment]
Yup!

**Comment by freekmurze** [comment]
We'll continue the conversation in #303
