### ISSUE TITLE
Resources won't publish

### ISSUE THREAD

**Issue by edgrosvenor** [spatie/laravel-tags#306]
This might actually be a bug in Package Tools or it might just be that the docs need to be updated to reflect a different method of publishing. I haven't looked at that package yet and only really know how to publish in a traditional service provider. What I do know is that when I run the publish migrations command in the docs `php artisan vendor:publish --provider="Spatie\Tags\TagsServiceProvider" --tag="migrations"` I get an error `Unable to locate publishable resources.` and no migration is published. Same if I attempt to publish the config.

Note: I edited my initial issue to correct my findings a little and clarify that it's general resource publishing that isn't working as expected.

**Comment by freekmurze** [comment]
Using the Package service provider, the suffix `tags-` is now required when publishing. I've updated the readme.

**Comment by Khalid3bdallah** [comment]
I had the same error 
`Unable to locate publishable resources.`
after using the command in the Readme
`sail artisan vendor:publish --provider="Spatie\Tags\TagsServiceProvider" --tag="tags-migrations`

**Comment by salvationarinze** [comment]
```
 sail artisan vendor:publish --provider="Spatie\Tags\TagsServiceProvider" --tag="migrations"
 sail artisan vendor:publish --provider="Spatie\Tags\TagsServiceProvider" --tag="config"
```
will work just fine
