### ISSUE TITLE
Broken Link in Readme

### ISSUE THREAD

**Issue by nasrulhazim** [spatie/laravel-tags#307]
Navigate to https://spatie.be/docs/laravel-tags/v2/introduction giving me the following error:

<img width="1343" alt="Screenshot 2021-03-15 at 9 33 02 AM" src="https://user-images.githubusercontent.com/10341422/111092602-75dabc00-8571-11eb-84f4-16803ce29c77.png">

**Comment by freekmurze** [comment]
I've corrected the link.
