### ISSUE TITLE
Bump laravel-translatable to ^5.0

### ISSUE THREAD

**Issue by RJFares** [spatie/laravel-tags#311]
Cannot update composer dep after upgrading to:
```
        "spatie/laravel-tags": "^4.0",
        "spatie/laravel-translatable": "^5.0",
```

Getting the following msg:
`Your requirements could not be resolved to an installable set of packages. `

`spatie/laravel-translatable[4.1.0, ..., 4.5.2] require php ^7.2 -> your php version (8.0.3) does not satisfy that requirement`
...
`spatie/laravel-tags 4.0.1 requires spatie/laravel-translatable ^4.6 -> satisfiable by spatie/laravel-translatable[4.6.0]`

**Comment by freekmurze** [comment]
Thanks for bringing this to my attention. This has been fixed in v4.0.2
