### ISSUE TITLE
Update publish migration and config conmands in README.md

### ISSUE THREAD

**Issue by benaf1** [spatie/laravel-tags#325]
The command `php artisan vendor:publish --provider="Spatie\Tags\TagsServiceProvider" --tag="migrations"` gave me an unable to locate publishable resources.  On https://spatie.be/docs/laravel-tags/v4/installation-and-setup was able to find updated command that works.  However both on README.md and on the docs site the command 'php artisan vendor:publish --provider="Spatie\Tags\TagsServiceProvider" --tag="config"' failed to locate publishable resources.  But the cammand `php artisan vendor:publish --provider="Spatie\Tags\TagsServiceProvider" --tag="tags-config"` worked.  Not much of a bug more of an update.  Didn't know where to put it.   Thanks for your awesome packages

**Comment by freekmurze** [comment]
I've updated this in our docs. Thanks!
