### ISSUE TITLE
Multi-DB inconsistency in accessing tagging tables

### ISSUE THREAD

**Issue by nargalzius** [spatie/laravel-tags#328]
So I followed the documentation on how to [create/define your own tag model](https://spatie.be/docs/laravel-tags/v4/advanced-usage/using-your-own-tag-model) (to be able to use it in a multi DB setup)

I'm able to set the tags and retrieve them (I'm even able to do it with the model and the tagging tables on different DBs)

However when I try to SEARCH for them using the `withAnyTags` (or pretty much any search-related) method, it doesn't seem to use the tables as implemented in the adjustment I made.

To replicate:

I have 2 DBs: **A** and **B**. As I mentioned earlier, I've applied the adjustments and set the taggables and tags table to DB **B**

I was able to set and retrieve tags even from model/entities from DB **A** (which means it's _correctly_ setting the tagging information on the right tables in **B**, even if we're tagging the model from **A**)

However, when I tried _searching_ for tags (`withAny`, etc) for tags in that very same model in **A** I was able to set/sync/retrieve tags with, it threw an error because it was trying to access the tagging information from **A** as well, instead of **B**

**Comment by nargalzius** [comment]
I'm pasting the actual error when trying to search for the tags from a model that's located in a different DB from the `tags` & `taggables` tables

---

Illuminate\Database\QueryException: SQLSTATE[42S02]: Base table or view not found: 
1146 Table '**DB_A**.tags' doesn't exist (SQL: 

select \*, CAST(**MODEL**.updated_at AS CHAR) as updated_at, 
CAST(**MODEL**.created_at AS CHAR) as created_at from \`**MODEL**\` 
where exists (select * from \`tags\` inner join \`**DB_B**\`.\`taggables\` 
on \`tags\`.\`id\` = \`**DB_B**\`.\`taggables\`.\`tag_id\` 
where \`**MODEL**\`.\`uuid\` = \`**DB_B**\`.\`taggables\`.\`taggable_id\` 
and \`**DB_B**\`.\`taggables\`.\`taggable_type\` = App\\**MODEL** 
and \`tags\`.\`id\` in (2)) and \`**MODEL**\`.\`deleted_at\` is null) 

---

Again to recap, the model (**MODEL**) is in **DB_A**, the `tags` and `taggable` tables are in **DB_B**

So everything in the select statement is actually correct - the model, that the `taggables` is taken from **DB_B**

The only thing wrong is the part where it was trying to access the `tags` table from **DB_A** (2nd line) - which I'm assuming it just assumed to be in the same DB as the model from which the `tags` relationship was invoked from.

It doesn't make sense though since the "override" of the tags method (which was in the documentation) already explicitly uses the new model for the tag (which I explicitly set to use the local DB). I even modified it to expliclity use the new tag (LocalTag)

```
public function tags(): MorphToMany
    {
        return $this
            ->morphToMany('App\LocalTag', 'taggable', $this->relationshipDBL('taggables'), null, 'tag_id')
            ->orderBy('order_column');
    }

`relationshipDBL()` is just my helper method to make sure it's explicitly prefixed with the right db (which in this case is **DB_B**

It's worth noting that searching for tags from a model in the **same** db (**DB_B**) works as intended, but I believe this is a genuine bug, because it's able to resolve separate model/tagging info when setting and retrieving - it only breaks when searching

**Comment by freekmurze** [comment]
Hi,

thanks for reporting this. As I'm not using this package in a multi-db context, I'm not going to invest time in fixing this.

Feel free to send a PR with tests that will fix this problem.

**Comment by AtomicDanny** [comment]
Hi Nargalzius, After reading your comment I assume you came pretty far with the implementation of Spatie's laravel-tags on a multi DB project. I'm currently also working on a multi DB project and I've started implementing Spatie's laravel-tags, but I've come to a little problem, perhaps you can help me!.

Context:  (I've never really used tags in any of my projects so please be understanding and patient with me)
I am currently working on a mobile application that uses 3 separate databases. The main db (aka "mysql") is for application user related data (e.g registration, orders etc.), the second db (aka mysql2) has data related to cosmetic items (perfumes, lotions, etc.) and the third db ( aka mysql3) has data related to technology ( laptop, phones etc). After requiring, publishing and migrating laravel-tags, a "tags" and "taggables" table were created in the main db (aka mysql). Reading the documentation that says to use HasTags on the model you want tags with, I set that up in the correct model (productLux) in the second db (aka mysql2) as well as the model (productTech) in my third db (aka msql3). 

I called upon a model from productLux and tried to add a tag to it but it gave me an error that there is no "taggables" table found in the database. So I copied the "taggables" table that was migrated to my main db and added it to mysql2 then executed the same function. Now it did work, but it added the "tag" to the tags table in my main db and the taggable information to the "taggables" table in mysql2. Now when I try to retrieve the model by calling upon the associated tag,  it returns an empty array. So what I did next was I copied the "tag" table (which contains the newly created tag) from main db and added it to mysql2. Now retrieving the model by tag does return the array with the correct data.

Problem: 
Now here's my problem. When I try to add a tag to a particular model it always adds the tag data to the "tag" table in my main db and the taggables information in the taggables table in my second db. In order for "withAnyTags" etc to work it requires both information to be in the same database. I tried defining my own tag model but to no avail (perhaps I'm doing it wrong).

Any pointers will help!!!
