### ISSUE TITLE
vendor:publish broken

### ISSUE THREAD

**Issue by dillingham** [spatie/laravel-tags#334]
```
php artisan vendor:publish --provider="Spatie\Tags\TagsServiceProvider" --tag="tags-migrations"
```
```
Unable to locate publishable resources.
```

**Comment by key60529** [comment]
Tested, you could use `php artisan vendor:publish --provider="Spatie\Tags\TagsServiceProvider" --tag="migrations"` to publish the migration file maybe just the function naming haven't updated in the package or something.

**Comment by freekmurze** [comment]
I'm thinking the instructions are correct when using the latest major version of the package.

**Comment by dillingham** [comment]
@freekmurze i recently tried installing and had this error? But no problem

**Comment by xewl** [comment]
It is matching v3 still because my environment's still on PHP7.4 I guess
![image](https://user-images.githubusercontent.com/245041/122742785-9b6d1500-d286-11eb-8786-04677633a117.png)

Sorry for troubling you with the misunderstanding Freek :) 
Current version indeed seems to be fine.
