### ISSUE TITLE
getTranslations() issue when editing tag

### ISSUE THREAD

**Issue by seanhudson** [spatie/laravel-tags#34]
I'm trying to update a tag, but I'm missing something.

```
$tag = Tag::findOrFail($id);
$tag->name = $request->name;
$tag->type = $request->type;
$tag->save();
```

But that throws this

`Type error: Return value of Spatie\Tags\Tag::getTranslations() must be of the type array, string returned`

**Comment by freekmurze** [comment]
This has been fixed in the newly tagged version `1.3.5`.

Run `composer update` to pull it in and try again.

Reopen this issue if the problem persists.
