### ISSUE TITLE
Option to disable translations

### ISSUE THREAD

**Issue by Reex11** [spatie/laravel-tags#350]
Hi!
Thank you for creating such a great package.

I (and many others as I imagine) would like to have the option to disable using translations.
Please vote if you need this functionality.

**Comment by Reex11** [comment]
I've created a [fork without translations](https://github.com/Reex11/laravel-tags/tree/disable-translations-v4) as a temp solution.

**Comment by onemoreahmad** [comment]
+1

**Comment by vesakk** [comment]
+1

**Comment by danielschweiger** [comment]
+1

**Comment by leonidlezner** [comment]
Hello guys,

I've a found a workaround for this issue: Setting the locale hardcoded to English.

This new function goes to your model:

    public function syncTagsWithoutLocale($tags)
    {
        $className = static::getTagClassName();

        $tags = collect($className::findOrCreate($tags, null, 'en'));

        $this->tags()->sync($tags->pluck('id')->toArray());

        return $this;
    }

And getting the name by 

`$tag->getTranslation('name', 'en')`

**Comment by freekmurze** [comment]
If this can disabled in an easy, and testable way, I'd accept a PR for this. Closing for now as my team won't actively work on this. If you need this, please start a discussion in the `ideas` category.

**Comment by SebastianSchoeps** [comment]
My workaround: extend Spatie's tag model with an own tag model (make sure to set this in the package's config) and override the `getLocale` method:

```
public static function getLocale()
{
    return 'noi18n';
}
```

A PR to the original Tag model like the following should do the job:
```
public static function getLocale()
{
    return config('tags.uses_translations') ? app()->getLocale() : 'noi18n';
}
```

**Comment by leonidlezner** [comment]
@SebastianSchoeps it is actually not a workaround, but the updated way of doing it :)

**Comment by SebastianSchoeps** [comment]
Funny :-). Thanks for your [PR](https://github.com/spatie/laravel-tags/pull/368)! Well, maybe my post helps someone who doesn't RTFM like me but searches the issues...

**Comment by simtsit** [comment]
In some projects (especially those that include international terms) we wish to avoid tag translation. 
Since this is my case, I kept the translation feature by adding the tag translation on-the-go. Check it out:
``
            $words = array('apple', 'orange', 'kiwi', 'banana', 'strawberry');
            foreach($words as $word)
            {
                $tag = \Spatie\Tags\Tag::findOrCreate($word); 
                $tag->setTranslation('name', 'en', $word);
                $tag->setTranslation('name', 'el', $word);
                $tag->save();
                $photo->attachTag($thistag);
            }
``
It will fill the database with entries like this
name ->{"el": "apple", "en": "apple"} 
slug -> {"el": "apple", "en": "apple"}

This way, switching language from English to Greek, the content to be displayed will always be the same.
PLUS: I have the translation functionality available, for those cases where I actually need to do tag translation.
And all this without hacking or overriding the core code.
