### ISSUE TITLE
Order issue on getWithType method

### ISSUE THREAD

**Issue by delta1186** [spatie/laravel-tags#366]
I ran across this today while I was implementing the Tags package.  Currently running latest 4.x version.

![image](https://user-images.githubusercontent.com/421307/140974721-936226ba-0afb-4603-b84a-66ba8dd26c6f.png)

Nothing special.  3 tags in the database.  Using Tinkerwell to get the collection of tags with a set type using the Tag::getWithTypes method.  As you can see from the screenshot it appears to be duplicating the order by column.

```
Illuminate/Database/QueryException with message 'SQLSTATE[42000]: [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]
A column has been specified more than once in the order by list. Columns in the order by list must be unique. 
(SQL: select * from [tags] where [type] = newsTag order by [order_column] asc, [order_column] asc)
```

**Comment by freekmurze** [comment]
Could you add a failing test for me to fix?

**Comment by delta1186** [comment]
Okay, I know exactly what the issue is now, but I am not sure how to write a failing test for it.  The reason is because the current suite of tests pass in MySql, but the package is failing when using MSSQL.  Apparently MySql is fine with executing the following select statement:

`select * from [tags] where [type] = newsTag order by [order_column] asc, [order_column] asc`

Notice the order by is duplicated.  This happens in the Tag::getWithTypes method.  

https://github.com/spatie/laravel-tags/blob/6b6426b138fa239aa3ab5ab87977a21c4bbec901/src/Tag.php#L60

In this method you add ->ordered() to the query, but if you look at the withType() scope that is also being applied here that ordered() method is also being applied there too.  Thus causing the query to have the duplicated order by column.

https://github.com/spatie/laravel-tags/blob/6b6426b138fa239aa3ab5ab87977a21c4bbec901/src/Tag.php#L26-L33

So my fix would be to just remove the ordered() call on the getWithTypes method since ordered() is already applied in the withType scope.  The other option would be to update eloquent-sortable to check if column has already been added to the orders array on the query builder.  

https://github.com/spatie/eloquent-sortable/blob/c2e8c4a223432b2fcc929110c575d56bd9b8ed10/src/SortableTrait.php#L38-L41

Let me know what you think.  I will go ahead and submit a PR for option 1, because I think it makes sense here.

**Comment by freekmurze** [comment]
Option 1 seems fine. If the tests pass, I'll likely merge it in.
