### ISSUE TITLE
Cannont publish "tags-migration" and "tags-config"

### ISSUE THREAD

**Issue by iamoat** [spatie/laravel-tags#385]
The two commands below use wrong tags. 

php artisan vendor:publish --provider="Spatie\Tags\TagsServiceProvider" --tag="tags-migrations”

php artisan vendor:publish --provider="Spatie\Tags\TagsServiceProvider" --tag="tags-config"

Need to update readme file to use the following.

php artisan vendor:publish --provider="Spatie\Tags\TagsServiceProvider" --tag="migrations”

php artisan vendor:publish --provider="Spatie\Tags\TagsServiceProvider" --tag="config"

Either update the readme or update the code in TagsServiceProvider

**Comment by eskiesirius** [comment]
this problem still exists

**Comment by austyuzhaninov** [comment]
Problem still exists. Pls update readme and docs page. Thx!
