### ISSUE TITLE
laravel-tags migrations and MariaDB

### ISSUE THREAD

**Issue by jarod51** [spatie/laravel-tags#39]
Hi

Can you confirm that migrations won't work with current MariaDB because of JSON type that does not exist in Maria ?

Regards

**Comment by freekmurze** [comment]
Yup, although I haven't tested it, you could try replacing `json` by `text` columns in the migrations.

afaik the team behind MariaDB is busy implementing `json` columns, so hopefully that'll be added soon.

**Comment by sandervanhooft** [comment]
For other readers: replacing `json` by `text` columns will not work with this package until MariaDB supports `json` columns.

Also see [this issue](https://github.com/spatie/laravel-tags/issues/22).

Consider migrating to the latest Mysql version, overriding the package to suit your needs, find another solution, or wait until the MariaDB team catches up.

**Comment by Kokil** [comment]
Any update on this ?
