### ISSUE TITLE
Get all available tags attached to a model

### ISSUE THREAD

**Issue by django23** [spatie/laravel-tags#41]
L.S.,

I wonder how to query `Tag::` in order to get all the tags attached to a specific model.

Or maybe a function like: `Model::existingTags()`

Kind regards,

**Comment by freekmurze** [comment]
You could do this:

```php
$tagIds = \DB::table('taggables')
   ->distinct()
   ->select('tag_id')
   ->where('taggable_type', YourModel::class)
   ->get()
   ->pluck('tag_id');

$tags = Spatie\Tags\Tag::whereIn('id', $tagIds)->get();
```

**Comment by ferrarafer** [comment]
Hi, i apologize to write in a closed issue but i have a doubt about what i read here.

I use this to get all tags attached to a model
`$tags = App\Models\ModelName::find(model_id)->tags`

Also if i want to get all models with their tags i do this
`$models = App\Models\ModelName::with('tags')->get()`

- Why do you not suggets one of this ways, that seems simpler than the other ones?

- Is there a reason to not use it like i do?

By the way, why is not in the documentation of the package this info? i see it usefull.

Thanks for this great package.

Kind regards,
Fernando.

**Comment by ronald2wing** [comment]
Yes. What is the correct way to eager load the tags?

**Comment by techguydev** [comment]
You can find a very nice what to do it here:

https://github.com/spatie/laravel-tags/issues/80
