### ISSUE TITLE
Get tags attached to record

### ISSUE THREAD

**Issue by tprifti** [spatie/laravel-tags#42]
Is there a function where i can get all tags attached to a record ?

For example lets get first article `$article = Article::find(1)->get();`
How to get all tags attached to `$article` ?

**Comment by tprifti** [comment]
According to #41 I did this : 

```php
$tagIds = \DB::table('taggables')
	          ->distinct()
                  ->select('tag_id')
                  ->where('taggable_id', $article->id)
	          ->get()
	          ->pluck('tag_id');

$tags = Tag::whereIn('id', $tagIds)->get();
return $tags;
```

**Comment by rahadur** [comment]
You can find best  [Solution](https://github.com/spatie/laravel-tags/issues/80) to do that. I think helpful for other.
