### ISSUE TITLE
withAnyTags doesn't filter results when using variable

### ISSUE THREAD

**Issue by sts-ryan-holton** [spatie/laravel-tags#424]
I'm using PHP 8.1, Laravel 9 and the latest version of this package. I have a fairly complex model called `Domain` and must paginate my results. A user has the ability to also search and sort by other options.

My `$search` variable is a string _(provided by an input field in my front-end)_, and then I'm attempting to add the `withAnyTags` method, I do have tags, one called "client" which when I hard-code into the method, and reload my page it does work, but parsing like this is giving me no results.

What am I missing?

```php
$domains = Domain::query();

if ($search != '') {
    $domains = $domains->withAnyTags((array) $search);
}

$domains = $domains->where('domains.user_id', Auth::id())
                    ->where(function ($sql) use ($search) {
                        $sql->orWhere('domains.domain', 'like', "$search%")
                          ->orWhere('domains.status', 'like', "$search%")
                          ->orWhere('domains.registrar', 'like', "$search%");
                    })
                    ->leftJoin('certificates', 'domains.id', '=', 'certificates.domain_id')
                    ->leftJoin('dns', 'domains.id', '=', 'dns.domain_id')
                    ->leftJoin('blacklists', 'domains.id', '=', 'blacklists.domain_id')
                    ->select('domains.*')
                    ->orderBy($sort[0] ?? 'domains.expires_on', $sort[1] ?? 'desc')
                    ->paginate((int) $perPage);
```

**Comment by dkroft** [comment]
Try:
- dumping a ->toSql() of the domain query?
- changing the   `"$search%"` to `$search.'%'`

**Comment by angeljqv** [comment]
@sts-ryan-holton so, still alive? any feedback?
