### ISSUE TITLE
Get tags in use and then order by name

### ISSUE THREAD

**Issue by 1stevengrant** [spatie/laravel-tags#426]
Sounds straight forward using

```php
$tagIds = DB::table('taggables')
            ->distinct()
            ->select('tag_id')
            ->where('taggable_type', 'App\Models\Video')
            ->orderBy('tag_id', 'asc')
            ->get()->unique()->pluck('tag_id');

$tags = \App\Models\Tag::whereIn('id', $tagIds)->orderBy('name', 'asc')->get();
```

but then I noticed a bunch of tags beginning with `A` in the middle of the collection.

Upon inspecting the database, I spotted that new tags seem to be saving as `{"en":"Sarah","es":"Sarah"}` in the name column whereas tags we've added in the past have been saved as `{"en": "Trust"}` (note the space after the colon messing with the `orderBy`).

Not sure if this is intentional or a bug? Not even sure if this is happening here or in the `nova-tags-field` package.

**Comment by hseyeved** [comment]
I hope this helps. I've been racking over this one for a while. I've gone about it the other way, starting with tags and then joining taggables.

`$tagIds = DB::table('tags')
                    ->distinct()
                    ->select('tag_id')
                    ->where('tags.type', 'model')
                    ->join('taggables', 'tags.id', '=', 'taggables.tag_id')
                    ->get()
                    ->unique()
                    ->pluck('tag_id');
        $this->tags = Tag::whereIn('id', $tagIds)->get()->sortBy('name', SORT_NATURAL|SORT_FLAG_CASE);`

**Comment by MotionPhix** [comment]
Late to the party but I think if you return values from the array, it works just fine. Something like this:

```
$tags = Tag::get()
      ->sortBy('name', SORT_NATURAL | SORT_FLAG_CASE)
      ->map(function ($tag) {
        return [
          'label' => $tag->name,
          'value' => $tag->id,
        ];
      })
      ->values();
```
