### ISSUE TITLE
Unable to sync tags when using types feature

### ISSUE THREAD

**Issue by jodiedunlop** [spatie/laravel-tags#43]
Unless I'm mistaken, there doesn't appear to be any way to sync tags when using 'types' to categorise tags.  

Is there a strategy for syncing tags when using the types feature, or any plans to implement this functionality?

**Comment by freekmurze** [comment]
`syncTags` actually can accept an array of `Tag` instances, not only strings. If you pass it `Tag` instances that use a type it should work just fine.

Does that solve your problem?

**Comment by jodiedunlop** [comment]
I could be doing something wrong, but when I do:

```php
// Add some tags with a type of 'colours'
$blue = Spatie\Tags\Tag::findOrCreate('blue', 'colours');
$red = Spatie\Tags\Tag::findOrCreate('red', 'colours');
$model->syncTags([$blue, $red]);   
```

Returns what you would expect:
```
$model->tagsWithType('colours');
=> Illuminate\Database\Eloquent\Collection {#653
     all: [
       Spatie\Tags\Tag {#699
         id: 1,
         name: "{"en":"blue"}",
         slug: "{"en":"blue"}",
         type: "colours",
         order_column: 1,
         created_at: "2017-04-25 23:18:17",
         updated_at: "2017-04-25 23:18:17",
         pivot: Illuminate\Database\Eloquent\Relations\MorphPivot {#649
           taggable_id: 2,
           tag_id: 1,
         },
       },
       Spatie\Tags\Tag {#710
         id: 2,
         name: "{"en":"red"}",
         slug: "{"en":"red"}",
         type: "colours",
         order_column: 2,
         created_at: "2017-04-25 23:18:23",
         updated_at: "2017-04-25 23:18:23",
         pivot: Illuminate\Database\Eloquent\Relations\MorphPivot {#706
           taggable_id: 2,
           tag_id: 2,
         },
       },
     ],
   }
```

```php
// Add another tag of a different type
$foo = Spatie\Tags\Tag::findOrCreate('foo', 'testing');
$model->syncTags([$foo]); 
```

Empty collection is returned:
```
$model->tagsWithType('testing');
=> Illuminate\Database\Eloquent\Collection {#714
     all: [],
   }
>>>
```

Is this expected behavior?

**Comment by freekmurze** [comment]
I suspect eloquent has cached the relation.

Could you try this: `$model->fresh()->tagsWithType('testing');`

**Comment by jodiedunlop** [comment]
That solves the empty collection problem,
but it seems that calling `$model->syncTags([$blue, $red])` and then calling $model->syncTags([$foo])` results in the `colours` set being dropped (only the `testing` set exists).

If my model needs to maintain two sets of tags; colours and testing, then how can I sync tags for each type since `syncTags()` will drop any of the other tags not included in the array (regardless of the type)?

**Comment by freekmurze** [comment]
Right. I'd accept a fully PR that adds this as a new function to the package.

If you don't have the time for a PR: the easiest way to achieve this is to manually disassociate all tags with a certain type from to model and the associate the tags you want.
