### ISSUE TITLE
detachTags on delete

### ISSUE THREAD

**Issue by loranger** [spatie/laravel-tags#44]
Hello,

I'm suprised deleting the model does not cascade deleting its taggable relationship (like media-library does, for example)

Is it a forgotten feature or is there a real reason (I didn't get yet) for not dropping those orphan relationships ?

Best,

Laurent

**Comment by freekmurze** [comment]
Hi, thanks for bringing this to my attention.  It would indeed be better if the records that represent the relationship should be deleted yes. I'd accept a PR that fixes this. I'd also be happy be with a PR that adds a failing test for me to fix.

**Comment by SandeeshS** [comment]
Detaching all the tags in the deleted event would be the easiest approach. But this won't work when the model gets mass deleted.

```
public static function bootHasTags()
{
    static::created(function (Model $taggableModel) {
        $taggableModel->attachTags($taggableModel->queuedTags);

        $taggableModel->queuedTags = [];
    });

    static::deleted(function (Model $taggableModel) {
        $taggableModel->syncTags([]);
    });
}
```

**Comment by loranger** [comment]
That's the way I did follow. I was fighting with the relationship in order to automatically remove any empty tags but this mass deletion bypass is quite annoying :/

**Comment by SandeeshS** [comment]
Well cleaning up any orphan relationship is better than nothing. Another solution would be to implement the event handler and provide an artisan command for garbage collection of orphaned relationships.

**Comment by freekmurze** [comment]
Should be fixed in latests version.
