### ISSUE TITLE
Tags also searchable via slug.

### ISSUE THREAD

**Issue by hikernl** [spatie/laravel-tags#45]
First of all, thanks for the great work.

While searching for tags i noticed you can only search for the name, not the slug.
Since the slug is normalized it would be easier to search for the slug.

For example i have a tag with the name: Hello.
``` Model::withAnyTags(['hello'])->get(); ```
Model is not found because the tag contains a uppercase H.

So Hello & hello are not the same.
It would be easier to search for a normalized tag, so uppercase doesn't matter.

**Comment by freekmurze** [comment]
I'm going to keep this as it is for now. In our projects slug names are unique. 
So if you need a function that uses the slugs to retrieve stuff, add it in your own project

**Comment by brentkozjak** [comment]
I believe this is actually a common use case.  Let's say, for example, you want to retrieve blog posts with a tag "Ferrari".  Usually you would use the tag in a URL, something like ``` /posts?tag=ferrari ``` and obtain the Tag "Ferrari" via the slug "ferrari".  In my project, I extended the ``` Spatie\Tags\Tag ``` model and added the following static method:

```
    public static function findFromSlug(string $slug, string $type = null, string $locale = null)
    {
        $locale = $locale ?? app()->getLocale();

        return static::query()
            ->where("slug->{$locale}", $slug)
            ->where('type', $type)
            ->first();
    }
```

This allows you to find a tag using ``` Tag::findFromSlug($slug) ``` , which is useful but still has limitations.  If anyone has any other solutions I'd be interested in seeing some code samples.

**Comment by mydnic** [comment]
I'm actually amazed that this is not a documented featured.

**Comment by orrd** [comment]
This isn't the same as how I would modify the project code to implement this feature, but this is a quick and dirty solution for anyone who just wants code they can **add to their own model** that doesn't involve modifying the Spatie's project's code.  

```
    public function scopeWithTagSlug($query, string $slug, string $type = null)
    {
        $locale = $locale ?? app()->getLocale();

        $tag = \Spatie\Tags\Tag::where("slug->{$locale}", $slug)
            ->where('type', $type)
            ->first();

        $query->whereHas('tags', function ($query) use ($tag) {
            $query->where('tags.id', $tag ? $tag->id : 0);
        });

        return $query;
    }
```
