### ISSUE TITLE
Sorting Tag Documentation Confusion?

### ISSUE THREAD

**Issue by bloggervista** [spatie/laravel-tags#46]
At this url `https://docs.spatie.be/laravel-tags/v1/advanced-usage/sorting-tags`

At these codes

```
//get all tags sorted on `order_column`
$orderedTags = Tags::ordered()->get(); 

//set a new order entirely
Tags::setNewOrder($arrayWithTagIds);

$myModel->moveOrderUp();
$myModel->moveOrderDown();

//move the tag to the first or last position
$myModel->moveToStart();
$myModel->moveToEnd();

$tag->swapOrder($anotherTag);
```

Do` $myModel `means Post Model (Just example for post it can be book or any) Instance or `\Spatie\Tags\Tag` Model instance?? 

I think `$myModel` should be `$tagModel` .

And in previous part of documentation we used `$myModel `for another thing  like Post Model, isn't it ?

Or i am confused :(?

**Comment by freekmurze** [comment]
`$myModel` should indeed be a `$tag`.

I've corrected this in the docs.

Thanks for bringing this to my attention.
