### ISSUE TITLE
Views and front end examples

### ISSUE THREAD

**Issue by mindmergedesign** [spatie/laravel-tags#48]
First of all, thank you so much for all the amazing packages. I am just learning Laravel and I am having a hard time getting the tags package to work. I followed all the installation steps but I am not really sure how I can add tags on the front end with a view. Are the sample code snippets supposed to be added in the model or should they be in the controller under their respective method (create, delete, etc)? 
Also, I was looking at a turorial on Laravel News (https://laravel-news.com/how-to-add-tagging-to-your-laravel-app) and they are using javascript (Selectivize) in the views to attach the tags. Does that work the same with this package? Is there a repo with a sample project using that where I can see how everything is put together?
Sorry about all the confusion, I am still trying to learn my way around Laravel.

**Comment by freekmurze** [comment]
Hi,

here's a bird's eye view of how we do it in our apps. We pass the name of every tag to a Blade View. On the client side we use [a Vue component](http://monterail.github.io/vue-multiselect/) that can render them. When submitting the form it will give back all the tags as strings. In the controller that handles the response we sync all the tags to the model.

Unfortunately I don't have a simple example of this usage. Providing a full tutorial on how to integrate it client side would take too much time. You could take a look at how we do it in our application template, but as it is a little bit more advanced, it might confuse you... Anyways here's the part on [how we sync the tags back to the model](https://github.com/spatie/blender/blob/master/app/Http/Controllers/Back/Traits/UpdateTags.php).

**Comment by tnorthcutt** [comment]
@freekmurze thanks for including those links to your implementation in Blender. I was able to use that as a rough guide for getting this working in my own app, which I'm thrilled with. Very much appreciated! ❤️
