### ISSUE TITLE
Conflict between `laravel-translatable` and `laravel-tags`

### ISSUE THREAD

**Issue by alexrififi** [spatie/laravel-tags#508]
I'm using the package `spatie/laravel-translatable`.

As written in the documentation [Customize the toArray method](https://spatie.be/docs/laravel-translatable/v6/advanced-usage/customize-the-toarray-method), I created my own trait `HasTranslations` with `toArray` method, that uses the trait from the package as `BaseHasTranslations`. 

```php
use Spatie\Translatable\HasTranslations as BaseHasTranslations;

trait HasTranslations
{
    use BaseHasTranslations;

    public function toArray()
    {
        //...
    }
}
```

This is necessary for compatibility with `spatie/laravel-data`

Then I installed the package `spatie/laravel-tags`, created own tag model that uses my own trait `HasTranslations`

```php
use App\Models\Traits\HasTranslations;

class Tag extends \Spatie\Tags\Tag
{
    use HasTranslations;
}
```

As a result, when creating a tag, I get an error
> Cannot make static method Spatie\Tags\Tag::getLocale() non static in class App\Models\Traits\HasTranslations

As I understand it, the problem is this:

- `Spatie\Translatable\HasTranslations` has non static method `getLocale`
- `Spatie\Tags\Tag` has static method `getLocale`

### ↪️ To Reproduce

```php
use Spatie\Translatable\HasTranslations as BaseHasTranslations;

trait HasTranslations
{
    use BaseHasTranslations;
}

class Tag extends \Spatie\Tags\Tag
{
    use HasTranslations;
}

it('can create a tag', function () {
    $tag = Tag::findOrCreateFromString('string');

    expect(Tag::all())->toHaveCount(1);
    expect($tag->getTranslation('name', app()->getLocale()))->toBe('string');
    expect($tag->type)->toBeNull();
});

// PHP Fatal error:  Cannot make static method Spatie\Tags\Tag::getLocale() non static in class HasTranslations
```

**Comment by AlexVanderbist** [comment]
Aha, good catch! We clearly haven't used this specific combination of packages while testing 😅. Unfortunately, I don't think there's an easy way to make both of these packages compatible without changing either method signature. However, I think changing this package's `getLocale` method non-static has a low enough impact to consider it in a next major version.

If you're up for the task, feel free to send a PR to make this method non-static and I'll look into getting that merged. In the meantime, I'd suggest forking the package to make it work for this specific use-case.
