### ISSUE TITLE
PDOException on syncTags()

### ISSUE THREAD

**Issue by huntercarter** [spatie/laravel-tags#54]
Here's the code from my controller:

> ...
>         $tags = explode(',',$request->input('tags'));
>         $userid = (int)\Auth::user()->id;
>         $url = \App\URL::where('id', '=', $id)->where('user_id', '=', $userid)->orderBy('updated_at', 'desc')->first();
>         $url->syncTags(['test1']);
>         $url->save();
>         return redirect('/l/'.\Hashids::encode($url->id));
>     ...

my model implements the trait

> class URL extends Model
> {
>     use \Spatie\Tags\HasTags;
> ...

and I receive this error when attempting to execute syncTags() for the first time after running the migration

> PDOException
> SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '>'$."en"' = ? and `type` is null limit 1' at line 1

**Comment by freekmurze** [comment]
This package only work on MySQL 5.7 or higher. You're probably on a lower version.

**Comment by huntercarter** [comment]
That was indeed it. I'm on 5.6. Thanks! Upgrading now.

**Comment by naeemz** [comment]
If you are using an older version of MySQL you need to make a change in below file. I solved it by updating one line of code.
/vendor/spatie/laravel-tags/src/Tag.php line No.60 comment or replace line with below code:

`//->whereRaw("name->{$locale}", $name)` comment out
`->where(\DB::raw( "json_extract(name, '$." . $locale . "')" ), '=', $name)`

**Comment by alhaji-aki** [comment]
I am using MariaDb10.2.22 but I still get this error
