### ISSUE TITLE
Database syntax error when adding tags

### ISSUE THREAD

**Issue by atmediauk** [spatie/laravel-tags#56]
I'm not sure if this is a bug but on a fresh setup and migration when I try and add an array of tags like:

```
//I'm using Laravel 5.4.30 with mariadb.

$tags = ['foo', 'bar', 'baz'];
$story-> attachTags($tags); //also tried syncTags
```

 I keep getting the following mysql error:

```
  [Illuminate\Database\QueryException]
  SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your
   MariaDB server version for the right syntax to use near '>'$."en"' = ? and `type` is null limit 1' at line 1 (SQL: select * from `tags
  ` where `name`->'$."en"' = foo and `type` is null limit 1)

  [PDOException]
  SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your
   MariaDB server version for the right syntax to use near '>'$."en"' = ? and `type` is null limit 1' at line 1

```

I'm not sure what could be causing this but it looks like it might have something to do with the translation feature? Although I'm not using that and just wanted english tags. It looks like it has something to do with an empty $ variable?

I also get the same issue when trying to add a single tag.

Thanks for your help, the package seems really useful!

**Comment by freekmurze** [comment]
This package only works with MySQL 5.7 or higher.

**Comment by nmpribeiro** [comment]
@freekmurze Actually, I'm seeing this in innodb_version 5.7.19. I'm using MariaDB 10.2.8
