### ISSUE TITLE
Compatible with MariaDB 10.2 JSON datatype? 

### ISSUE THREAD

**Issue by dmachiavello** [spatie/laravel-tags#57]
Will this package work with MariaDB's json datatype in 10.2+ ? Currently we're running mariadb 10.1 and want to see if upgrading to 10.2 is worth it.

**Comment by freekmurze** [comment]
I honestly don't know. Try it out and report back here 👍

**Comment by dmachiavello** [comment]
I was just able to try this with a vanilla install of MariaDB 10.2.7, and it failed. Two things to note:

1. Even though the create table used JSON as the column's datatype, maria just silently converted it to TEXT instead (no errors where thrown).
2. I suspect the differences in the JSON syntax are different between maria's eventual JSON datatype and the one used by spatie/laravel-tags. 

As much as I'd like to use this project, in our current production environment, it looks like we cannot use this.

**Comment by freekmurze** [comment]
Too bad... Thanks for your work investigating this.

**Comment by sebastiandedeyne** [comment]
> Even though the create table used JSON as the column's datatype, maria just silently converted it to TEXT instead (no errors where thrown).

Could it be that Laravel doesn't support json with MariaDB yet?

**Comment by dmachiavello** [comment]
I thought so too, so one of my tests I did was exported the create table from MySQL 5.7 and got this:
```
CREATE TABLE `tags` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `name` json NOT NULL,
  `slug` json NOT NULL,
  `type` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `order_column` int(11) DEFAULT NULL,
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
```
Then i manually ran it MariaDB and ran `SHOW CREATE TABLE` on it and the following was output:
```
CREATE TABLE `tags` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `name` text COLLATE utf8mb4_unicode_ci NOT NULL,
  `slug` text COLLATE utf8mb4_unicode_ci NOT NULL,
  `type` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `order_column` int(11) DEFAULT NULL,
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
```

Again, I'll just say that I'm not a DBA, so perhaps there are additional plugins that are required, but as for vanilla install, sadly, it doesn't appear to work.

**Comment by tnorthcutt** [comment]
@dmachiavello even though mariadb is just aliasing `json` to `text`, is there a reason this package wouldn't work with MariaDB 10.2.7+? I guess what I'm wondering is what you mean by "it failed"? Thanks! 😄

**Comment by dmachiavello** [comment]
@tnorthcutt I ran this test many months ago, and I remember at the time the issue was that the package wasn't working, like adding tags, searching for tags, etc. I suspected a syntax difference with json searching between Maria and Mysql. I haven't tried this recently, though, so I welcome anyone else to test this as well since in our enterprise we're using mariadb.

**Comment by sebastiandedeyne** [comment]
> even though mariadb is just aliasing json to text, is there a reason this package wouldn't work with MariaDB 10.2.7+

That only applies to migrations in Laravel, querying json field contents (with `->`) doesn't work with MariaDB iirc.

**Comment by tnorthcutt** [comment]
@dmachiavello @sebastiandedeyne thank you both for the reply. Very helpful 👍
