### ISSUE TITLE
Locale with retrieving WithAnyTags

### ISSUE THREAD

**Issue by markoseigra** [spatie/laravel-tags#59]
Is it possible to add locale as an optional parameter to pass when calling WithAnyTags or WithAllTags, for that matter, so it can pass it to convertToTags ? Or is there some other way and I'm doing something wrong. 

Cheers.

**Comment by freekmurze** [comment]
The functions you mentioned also accept an array of Tag instances. You could first manually fetch the tags your interested in and than pass those on to `withAnyTags` or `withAllTags`
