### ISSUE TITLE
Example in Documentation does not work

### ISSUE THREAD

**Issue by MannikJ** [spatie/laravel-tags#63]
Hi,

maybe I am just missing something, but as far as I see, the following example code from the docs is invalid:
```php
$tag = Tag::create('gossip', 'newsTag');
$tag2 = Tag::create('headline', 'newsTag');
```

Since the Tag model does not overwrite the create method from the eloquent model you have to write something like this instead:

```php
$tag = Tag::create([
            'name' => 'gossip', 
            'type' => 'newsTag'
]);
$tag2 = Tag::create([
            'name' => 'headline', 
            'type' => 'newsTag'
]);
```

**Comment by freekmurze** [comment]
It should be `findOrCreate` instead of  `create`. Fixing the docs now.
