### ISSUE TITLE
SQLSTATE[HY000]: General error: 2036 (SQL: select * from `tags` where `name`->'$."nl"' = testtag and `type` is null limit 1)

### ISSUE THREAD

**Issue by disto** [spatie/laravel-tags#64]
I am using version 1.4 
On my dev machine it works like a charm, but today I deployed it to my acceptation server and
now I am getting the error message mentioned in the title of this issue, while using Tag::findOrCreate.

When I copy and past the sql statement in the query runner of SequelPro I still get an error message
But when I put quotes around the 'testtag' word, the query run's perfectly

I am using Mysql version 5.7.19 on my dev machine an 5.7.18-6 on my acceptation server
I am using php7.0.10 on my dev machine and php7.0.20 on my dev  acceptation server

Another difference I can see is that on my dev machine mysqlnd is loaded, but not on the acceptation server.

Please advice.

Kind regards

**Comment by sebastiandedeyne** [comment]
Apparently the mysqlnd makes the difference... Found this link and it seems to be an issue related to Laravel, not this package:

https://laracasts.com/discuss/channels/eloquent/json-column-problem-with-mysql57-and-laravel52/replies/195067

Installing mysqlnd should do the trick though!

**Comment by NesCafe62** [comment]
For those who still getting error even after mysqlnd version is actual.
In `config/database.php` add `PDO::ATTR_EMULATE_PREPARES => true`:
```
'mysql' => [
    /* ... */
    'options'   => [PDO::ATTR_EMULATE_PREPARES => true]
],
```
