### ISSUE TITLE
SQLSTATE[HY000]: General error: 2036 (SQL: select * from `tags` where `name`->'$."nl"' = testtag and `type` is null limit 1

### ISSUE THREAD

**Issue by disto** [spatie/laravel-tags#65]
Hi,

Apparently we needed to upgrade to php7.1 from 7.0.20 to get mysqlnd working.
But now the csrf token verification is not working anymore.
TokenMismatchException in VerifyCsrfToken.php line 68:

Did you encounter such a error?

thx 

Kind Regards

**Comment by sebastiandedeyne** [comment]
Sorry, don't know what's going on here... 

Please open an issue on the Laravel repository or a thread on Laracasts for issues not related to this package.
