### ISSUE TITLE
Can't install package on Laravel 5.4

### ISSUE THREAD

**Issue by JafarbadarnehAG** [spatie/laravel-tags#66]
As mentioned in the Docs, 
> This package requires Laravel 5.3 or higher, PHP 7.0 or higher and a database that supports json fields such as MySQL 5.7 or higher.

My php version is 7.1.2 operating laravel 5.4 with Mysql database 5.7. When i head to install the package via composer command : `composer require spatie/larave-tags` it resulted in a dependency error.
![screenshot from 2017-09-14 12-49-49](https://user-images.githubusercontent.com/21292175/30429391-f6fcae12-995f-11e7-935c-80a9ecd9f5d2.png)

As shown in the error log, it requires illuminate/database ~5.5.0 which is i think operates with Laravel 5.5.

**Comment by freekmurze** [comment]
The docs were wrong: the latests version of this package requires Laravel 5.5. If you need to install it into an older version of the framework use `v1`.
