### ISSUE TITLE
Sync a single Tag

### ISSUE THREAD

**Issue by Kenilik** [spatie/laravel-tags#67]
I would appreciate some help with the following problem:
I need to toggle (attach/detach) a tag to a model but to leave any other tags alone.

Consider the following:
There are 4 tags in the DB Tag1, Tag2, Tag3, Tag4
$model has Tag1, Tag2 and Tag3 attached.

I want to call something like a 'toggleTag' function and see the following behaviour:
- $model->toggleTag('Tag1') // $model now has Tag2 & Tag3.
- $model->toggleTag(['Tag3', 'Tag4']) // $model now has Tag2, & Tag4
- $model->toggleTag(['Tag1', 'Tag5']) // $model now has Tag1, Tag2, Tag4 & Tag5 (Tag5 is created, and with type if passed).

I am also doing all this using tag types so I need to allow for that as well.

I must be missing something but I'm struggling to see whether or not a given tag exits on a model (which will allow me to attach, detach or create and attach).

Thanks,

**Comment by ojsoft** [comment]
Just add this to your Model:

```
public function toggleTag($toggletag)
{
   foreach($this->tags as $tag) {
      if ($tag->name === $toggletag) {
         $this->detachTags($toggletag);
         return;
      }
   }
   $this->attachTag($toggletag);
}
```
