### ISSUE TITLE
QUESTION -> migration from rtconner/laravel-tagging

### ISSUE THREAD

**Issue by schonhose** [spatie/laravel-tags#70]
Is there an easy way to migrate my tags from the package rtconner/laravel-tagging to this package? The author of the other package has abandoned the package and composer suggests using the package from Spatie.

The only problem is the migration of the existing tags. Before I start writing a migration command I would like to know if someone has already written such a feature.

**Comment by cmosguy** [comment]
@schonhose i don't know the answer to this question, but I have a quick question for you?  Why are you migrating over to this package?  I am asking because I am researching an optimal tagging package for my project, and was curious what is your motivation?

**Comment by freekmurze** [comment]
@cmosguy `rtconner/laravel-tagging` isn't maintained anymore.

**Comment by schonhose** [comment]
The interesting thing I have right now is that I am running Laravel 5.1. The package from Spatie requires a higher version. This makes the migration somewhat more interesting, The way I am approaching it now is to make a copy of my database, a fresh installation of Laravel 5.5, install both packages and create a loop that gets the tags from `rtconner/laravel-tagging` and use the methods from `spatie/laravel-tags` to insert it into the new structure. Tedious, but doable. 

Any other suggestions are welcome!

**Comment by AlexVanderbist** [comment]
The best way to go about this is probably to write the db migration you mentioned. Schema's don't look too different (apart from tag groups). 

Feel free to share any code you've written to do the migration as well! 👍

Closing this for now.
