### ISSUE TITLE
SQLSTATE[42000]: Syntax error or access violation: 1064 

### ISSUE THREAD

**Issue by naknode** [spatie/laravel-tags#72]
Hi all, I am trying to do an example of tagging. I have appended my model with the `HasTags` trait and when I do 

```
        $id = Questions::create([
            'body' => request('title'),
            'skillset_id' => request('skillsetId'),
            'tags' => ['red', 'blue']
        ])->id;
```

I get:

```SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '>'$."en"' = ? and `type` is null limit 1' at line 1 (SQL: select * from `tags` where `name`->'$."en"' = red and `type` is null limit 1)```

I am on
- Windows 10
- MariaDB 10.3.2
- MySQL 5.7.19

I have successfully installed and added the migration tables, but the creating of tags is where I fail.

**Comment by freekmurze** [comment]
The error message points out that your are using MariaDB. Our package leverages JSON columns which are only supported by MySQL.

**Comment by naknode** [comment]
Thanks. I read somewhere that MariaDB 10.3.x supported `JSON` columns -- I guess not. I'll have to rip away MariaDB for MySQL, I suppose.

**Comment by naeemz** [comment]
If someone wants just to get rid of this issue.  I solved it by updating one line of code.
Update _/vendor/spatie/laravel-tags/src/Tag.php_ line No.60 comment or replace line with below code:

`//->whereRaw("name->{$locale}", $name)`
`->where(\DB::raw( "lcase(json_unquote(json_extract(name, '$._" . $name . "')))" ), '=', strtolower( $locale ))`

**Comment by nilsringersma** [comment]
Thanks @naeemz, works like a charm!

**Comment by netr** [comment]
I actually had some problems with the above fix.. Was creating duplicate rows.. I fixed it with 

`->where(\DB::raw( "json_extract(name, '$." . $locale . "')" ), '=', $name)`

**Comment by vivekaviva** [comment]
Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'JSON NOT NULL COMMENT '(DC
  2Type:json_array)'' in symfony 4

**Comment by freekmurze** [comment]
@vivekaviva use a recent mysql db instead of mariadb

**Comment by fredbradley** [comment]
Can I ask, if a fix has been found (as @netr details) why can that not be added to the package, as opposed to the response of "use mysql instead"?

**Comment by dylanglockler** [comment]
So deploying on Cloudways, which uses MariaDB, eliminates me from using this package I suppose?

**Comment by dylanglockler** [comment]
Sounds like you're on a MariaDB, which doesn't support json as a data type. I converted to MySQL to resolve the issue.

**Comment by desidude03** [comment]
i am still with this error. i can't even find spatie folder within vendor folder

**Comment by BobbyBorisov** [comment]
@naeemz how this fixes the problem? when i try to do artisan migrate everything blows up? DO you know the solution?

**Comment by dylanglockler** [comment]
“Blows up” doesn’t really provide any useful information. What is the error message?

**Comment by BobbyBorisov** [comment]
@dylanglockler there were some issues, cannot remember but fixed it. Maybe the problem was my mariadb version. However I created a fork for myself in which i do not use multilanguages, cause i don't need them.

**Comment by darki73** [comment]
Well, this is strange. Other spatie packages use json, like:
- [https://github.com/spatie/nova-translatable](spatie/nova-translatable)
- [https://github.com/spatie/laravel-translatable](spatie/laravel-translatable)

And i have no problem using them on the MariaDB 10.3, i can even define `json` type column in the migration, yet this one package is always complaining about `select * from `tags` where `name`->'$."en"' =`.
And yes, for many people switching the DBMS engine is not an option as they usually do have other projects running on that specific instance of the engine.

There should be a better way to solve this issue, rather than @freekmurze 's 

> use a recent mysql db instead of mariadb

Don't get me wrong, it is an open source project, and spatie delivers best packages which are easy to install and use, but if other packages can already manage json columns in MariaDB, why this one should be left out of the party?

**Comment by darki73** [comment]
For those, who do not want to edit the source code in the vendor folder, there is obviously an option:

1. **Create new class which will extend the original Tag.php class**

```
<?php namespace App\Classes\Vendor\Spatie\LaravelTags;

/**
 * Class Tag
 * @package App\Classes\Vendor\Spatie\LaravelTags
 */
class Tag extends \Spatie\Tags\Tag {

    public static function findFromString(string $name, string $type = null, string $locale = null)
    {
        $locale = $locale ?? app()->getLocale();

        return static::query()
            ->where(\DB::raw( "json_extract(name, '$." . $locale . "')" ), '=', $name)
            ->where('type', $type)
            ->first();
    }

}

```

2. **Create new trait, so the new Tag class can be used instead of the old one**

```
<?php namespace App\Classes\Vendor\Spatie\LaravelTags;

trait HasCustomTags {

    public static function getTagClassName(): string {
        return Tag::class;
    }

}

```

3. **And finally, on the model just add the following code:**
```
use HasTranslations, HasTags, HasCustomTags {
     HasCustomTags::getTagClassName insteadof HasTags;
}
```

This approach will allow you to successfully deploy code to the server from your local environment without loosing the functionality.

**Comment by sindhu13** [comment]
> 
> 
> For those, who do not want to edit the source code in the vendor folder, there is obviously an option:
> 
>     1. **Create new class which will extend the original Tag.php class**
> 
> 
> ```
> <?php namespace App\Classes\Vendor\Spatie\LaravelTags;
> 
> /**
>  * Class Tag
>  * @package App\Classes\Vendor\Spatie\LaravelTags
>  */
> class Tag extends \Spatie\Tags\Tag {
> 
>     public static function findFromString(string $name, string $type = null, string $locale = null)
>     {
>         $locale = $locale ?? app()->getLocale();
> 
>         return static::query()
>             ->where(\DB::raw( "json_extract(name, '$." . $locale . "')" ), '=', $name)
>             ->where('type', $type)
>             ->first();
>     }
> 
> }
> ```
> 
>     1. **Create new trait, so the new Tag class can be used instead of the old one**
> 
> 
> ```
> <?php namespace App\Classes\Vendor\Spatie\LaravelTags;
> 
> trait HasCustomTags {
> 
>     public static function getTagClassName(): string {
>         return Tag::class;
>     }
> 
> }
> ```
> 
>     1. **And finally, on the model just add the following code:**
> 
> 
> ```
> use HasTranslations, HasTags, HasCustomTags {
>      HasCustomTags::getTagClassName insteadof HasTags;
> }
> ```
> 
> This approach will allow you to successfully deploy code to the server from your local environment without loosing the functionality.

i get an error,
Trait 'App\HasCustomTags' not found

**Comment by darki73** [comment]
@sindhu13 
You have to strictly follow the paths mentioned in the "definition" of trait/class if you don't understand how to modify them so they are compatible with your application.  

In case of Tag class, the path is:  
```/app/Classes/Vendors/Spatie/LaravelTags/Tag.php```  

In case of HasCustomTags trait, the path is:  
```/app/Classes/Vendor/Spatie/LaravelTags/HasCustomTags.php```

By the way, ```use App\Classes\Vendor\Spatie\LaravelTags;``` is not correct definition, you cannot reference a folder, you have to explicitly reference the item you want to import to your class, in the case of trait, the correct way is: ```use App\Classes\Vendor\Spatie\LaravelTags\HasCustomTags;```

**Comment by mobeelco** [comment]
@darki73 
Thank you
Its Worked

**Comment by riyuk** [comment]
@freekmurze why is this issue closed with a solution, which actually works both ways (mariadb&mysql)?
MariaDB is widely used and it actually *supports* json by 10.2.7.

**Comment by Ahmed-Radi** [comment]
> If someone wants just to get rid of this issue. I solved it by updating one line of code.
> Update _/vendor/spatie/laravel-tags/src/Tag.php_ line No.60 comment or replace line with below code:
> 
> `//->whereRaw("name->{$locale}", $name)`
> `->where(\DB::raw( "lcase(json_unquote(json_extract(name, '$._" . $name . "')))" ), '=', strtolower( $locale ))`
> 
> UPDATED:
> @netr is right, above mentioned code generate duplicate rows: below is working fine:
> `->where(\DB::raw( "json_extract(name, '$." . $locale . "')" ), '=', $name)`
> 
> Thanks @netr

i me not find this path in laravel folders
