### ISSUE TITLE
Can't add tags

### ISSUE THREAD

**Issue by timgavin** [spatie/laravel-tags#73]
MySQL: 5.7.20
Laravel: 5.5.21
PHP: 7.1.3

Every time I try to add tags I receive this error

```
Call to undefined method Illuminate\Database\Query\Builder::syncWithoutDetaching()
```

I've tried using `attachTags()`, `syncTags()` and `attachTag()`, and all give the same error.

```
$post->attachTags(['one', 'two']);
$post->syncTags(['one', 'two']);
$post->attachTag('tag 1');
```

I'm attempting to attach tags right after creating a `$post`

**Comment by freekmurze** [comment]
All tests around this functionality proves that this works. `syncWithoutDetaching` is part of Laravel. Does your `Post` class extend `Model`?

**Comment by timgavin** [comment]
```
use Illuminate\Http\Request;
use Illuminate\Database\Eloquent\Model;
use Spatie\MediaLibrary\Media;
use Spatie\MediaLibrary\HasMedia\Interfaces\HasMediaConversions;
use Spatie\MediaLibrary\HasMedia\HasMediaTrait;
use Spatie\Image\Manipulations;
use Spatie\Tags\HasTags;

class Post extends Model implements HasMediaConversions
{
    use HasMediaTrait, HasTags;
    ...
```

**Comment by freekmurze** [comment]
Could you PR a failing test?

**Comment by timgavin** [comment]
I figured it out. I had previously implemented my own tagging method and didn't remove the `tags()` relationship in the Post model. :/
