### ISSUE TITLE
Has Tag

### ISSUE THREAD

**Issue by liran-co** [spatie/laravel-tags#74]
Is there an easy way to check if a model currently has a tag? Something like $model->hasTag('')?

**Comment by freekmurze** [comment]
`$model->tags->count()`

**Comment by liran-co** [comment]
Sorry, guess I wasn't clear. I mean to check if it has a specific tag $model->hasTag('hello world')

**Comment by freekmurze** [comment]
```php
$model->tags->contain(function(Tag $tag) use ($name) {
   return $tag->name === $name;
});
```
