### ISSUE TITLE
Get all the tags from an Entity Namespace

### ISSUE THREAD

**Issue by rahadur** [spatie/laravel-tags#80]
I am new in Laravel as well as i am first time using your ` Service Provider `  I have a `questions` table in my MySQL database where every question belongs To many tags. I setup and config your provider properly. Here is my code. 

`in App\Question`
```php
class Question extends Model
{
    use HasTags;


}
```
`in App\Http\Controller`
```php
class QuestionsController extends Controller
{
    ......
    public function store() {
        // create and save tags in tags table properly.
    }

}
```

`in Terminal`
```bash
>> $questions = App\Question::all();
=> Illuminate\Database\Eloquent\Collection {#833
     all: [
       App\Question {#805
         id: 1,
         title: "This is my development first question",
         slug: "this-is-my-development-first-question",
         details: "<p><strong>Lorem Ipsum</strong> is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's s
tandard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.</p>",
         approved: 0,
         created_at: "2017-12-16 06:54:10",
         updated_at: "2017-12-16 06:54:10",
       },
       App\Question {#750
         id: 2,
         title: "This is my development first question",
         slug: "this-is-my-development-first-question",
         details: "<p>This package offers taggable behaviour for your models. After the package is installed the only thing you have to do is to add th
e <code>HasTags</code> trait to an Eloquent model to make it taggable.</p>",
         approved: 0,
         created_at: "2017-12-16 08:25:29",
         updated_at: "2017-12-16 08:25:29",
       },

// no associate tags return
>> $q[0]->tagsWithType('App\Question');
=> Illuminate\Database\Eloquent\Collection {#825
     all: [],
   }

```

How This will return all the tags that belongs to the given Entity Namespace. like [https://cartalyst.com/manual/tags/2.0#get-all-the-tags-from-an-entity-namespace](url) this Provider

Thank you

**Comment by rahadur** [comment]
After long try i am finally able to find my solution. The solution is when you want to retrieve tags which associate with your post or other model you have to use this chain method which is not mention in document.

```php
$newsItem= App\NewsItem::find(1);

// return  all associate tags of news item.
$newsItem->tags()->get();
```

i hope it will save your time.

**Comment by roro6969** [comment]
Another solution is to append "Tags" to your model : 

`class Post extends Model
{
    use HasTags;

    protected $appends = ['Tags'];

    public function getTagsAttribute()
    {
        return $this->tags()->get();
    }
`
Then in you controller you can get all post with tags : 

`$lists = $postModel->paginate(10);`

**Comment by techguydev** [comment]
This should be documented, quite useful.

**Comment by sfinktah** [comment]
Here's an absurdely complex example that perhaps someone much smarter than me can optimize.  

Use case: retrieve resource **and** all associated tags **as an array** in a single SQL (*cough* MySQL) statement.  _note, had to use JSON encoded array, but best I could do._

Output:
```
[
      "name" => "Resource Name",
      "tags" => "["automotive", "australian"]",
], ...   
```

Hideous source:
```php
use App\Models\Site;

$results = Site::withoutTags(['private'], 'site')
    ->select(['name', 'tags'])
    ->join(DB::raw(
        <<<EOT
                (SELECT taggable_id, JSON_ARRAYAGG(tag) AS tags
                FROM (SELECT JSON_EXTRACT(name, "$.en") AS tag, taggable_id
                      FROM `tags`
                               INNER JOIN `taggables` ON `tags`.`id` = `taggables`.`tag_id`
                        AND `taggables`.`taggable_type` = 'App\\\\Models\\\\Site') AS site_tags
                GROUP BY taggable_id) AS json_tags
                EOT
    ), function ($join) {
        $join->on('taggable_id', '=', 'id');
    });

$results->get()->toArray();
```

And I do realise that it would be [probably] be possible to achieve the same thing with a bunch of Builder commands, and then some Collection magic, but it just hurt too much.
