### ISSUE TITLE
Ability to customize slugs

### ISSUE THREAD

**Issue by quangbuule** [spatie/laravel-tags#85]
Hi guys,

This one always reset slug, so we couldn't set custom slugs:
https://github.com/spatie/laravel-tags/blob/master/src/HasSlug.php#L12

What do you think about this?

**Comment by freekmurze** [comment]
You can override the `generateSlug` function on your model if you need some custom logic.

**Comment by FarhanShares** [comment]
Hey! Thanks for the laravel-tags.

I looked around the docs & issues; tried finding a way of it. 

What if I do not have a model (using the one provided in-built, i.e. Spatie\Tags\Tag) and I want to have a custom slug, how do I do so? It would be nicer to have an option.

Thanks again.

**Comment by guoxiangke** [comment]
Hi, I really need custom slug, thanks.
<img width="475" alt="image" src="https://github.com/spatie/laravel-tags/assets/1160703/9eb1ec49-f5bd-4868-bee6-b17fe8dc99bb">
