### ISSUE TITLE
Duplicated tags

### ISSUE THREAD

**Issue by gborgonovo** [spatie/laravel-tags#86]
Hi there,
every time I save a Model with tags, tags are duplicated in the tags table.
I'm using
`$page->syncTags(array_map('trim',explode(',',$request->tags)));`
Where `$request->tags` is a comma separated list of tags.

If I use
`$page->attachTags(array_map('trim',explode(',',$request->tags)));`
Tags are duplicated as well and, even worst, multiple idenatical tags are attached to the page.
 
In the Page Model definition I have added 
`    public function getTagsAttribute()
    {
        return implode(',',$this->tags()->pluck('name')->toArray());
    }`
To create the comma separated list to show in the input form.

This is the (sqlite)DB:
`30|{"en":"due tag"}|{"en":"due-tag"}||30|2018-01-17 22:21:44|2018-01-17 22:21:44`
`31|{"en":"Un tag"}|{"en":"un-tag"}||31|2018-01-17 22:23:02|2018-01-17 22:23:02`
`32|{"en":"due tag"}|{"en":"due-tag"}||32|2018-01-17 22:23:02|2018-01-17 22:23:02`
`33|{"en":"Un tag"}|{"en":"un-tag"}||33|2018-01-17 22:23:16|2018-01-17 22:23:16`
`34|{"en":"due tag"}|{"en":"due-tag"}||34|2018-01-17 22:23:16|2018-01-17 22:23:16`
`
As you see the slug is the same several times.

Any idea of how I could solve this issue?
Thank you! ...and compliments!

**Comment by freekmurze** [comment]
Could you PR a failing test?

**Comment by nilsringersma** [comment]
@gborgonovo Did you manage to further investigate or solve this problem? I'm running into the exact same issue.

Thanks!

**Comment by gborgonovo** [comment]
I'm sorry, I didn't. The feature was not primary for my project and I wont get stuck for it.

**Comment by ctf0** [comment]
btw this also could happen if u used `syncTagsWithType`, for example

- if u have a tag with `type == null` & u tried to attach the tag to a model but under a new type name.
now the package will simply create a new tag with the same name under the new type, which will lead into having 2 identical tags attached to the model, one with type and one without.

  am not sure if this intentional or a side effect, but this might be a one way to have a duplicate tags.

- as for the `attachTags` i use `syncTags` in model `store` and `update` without any issues, as thats what u will mostly be after anyway.

**Comment by manniL** [comment]
This happened to me when I made the `tags` attribute of my model `fillable` and used `syncTags` or `attachTags` additionally.

**Comment by freekmurze** [comment]
If you have problems around this, please PRs failing tests for us to fix.

**Comment by dalholm** [comment]
@gborgonovo @nilsringersma 
Maybe it's old news, but for others with same problem this could be helpful. 


I just had similar problem, using `$mode->syncTagsWithType ($tags, 'type')`.

When having the model guard set to`$guarded = []` and update with `$request->all()` the model goes by its traits and creating the tags without the type. And when i later run `$category->syncTagsWithType($request->input('tags'), 'skills');` that will create new tags with types which does not exist. (others have no type related to them)
```php
Category.php

protected $guarded = []; // use $fillable instead

///////

public function update(CategoryRequest $request, $id)
{
      $category = Category::findOrFail($id);
      $category->update($request->all());

      $category->syncTagsWithType($request->input('tags'), 'skills');
}    
```

Solution was simple, dont be a lazy as and fill in the `$fillable` instead. :)
