### ISSUE TITLE
Feature request: tag groups

### ISSUE THREAD

**Issue by francoism90** [spatie/laravel-tags#88]
Would it be possible to divide tags into groups?
```
tag: The Simpsons => group: Series
tag: The Office => group: Series
tag: Homer Simpson => group: Stars
```

Thanks!

**Comment by freekmurze** [comment]
Currently this is not possible, but I'd accept a PR that adds a `tag_model` key to the config file that makes it possible to specify your own `tag` model.

**Comment by francoism90** [comment]
@freekmurze Think `types` have been invented for the thing I want to achieve. :)

Thanks anyway, maybe I'll take a look at it later. :)

Doc: https://docs.spatie.be/laravel-tags/v2/advanced-usage/using-types
