### ISSUE TITLE
Syntax error or access violation: 1064

### ISSUE THREAD

**Issue by jerauf** [spatie/laravel-tags#89]
I'm getting this error:

`Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '>'$."en"' = ? and `type` is null limit 1' at line 1 (SQL: select * from `tags` where `name`->'$."en"' = tag 1 and `type` is null limit 1)`

Why would that be happening?

**Comment by freekmurze** [comment]
Your database probably doesn’t have support for JSON colums.

Try using MySQL 5.7 or higher.
