### ISSUE TITLE
Adding tags as part of model creation not working

### ISSUE THREAD

**Issue by minedun6** [spatie/laravel-tags#92]
I just started using this package so I having been fiddeling with it that much but the first method I used didn't work.

```php
//create a model with some tags
$newsItem = Group::find(id)->stories()->create([
   'name' => 'testModel',
   'tags' => ['tag', 'tag2'],
]);
```

this creates the model correctly but does not attach the tags correctly.
Am I missing something ?

**Comment by TVke** [comment]
Hi @minedun6 

Are you sure you have defined the `HasTags` trait on your story model?

**Comment by Moppet12** [comment]
Add "tags" to your **protected fillable array**

**Comment by rokde** [comment]
Won't work:

Model:
```php
class Customer extends Model {
  use HasTags;

  protected $fillable = ['tags'];
}
```

Using:
```php
$c = Customer::first();
$c->attachTag('Tag1');
```

Throws exception:
Illuminate\Database\QueryException with message 'SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '>'$."de"' = ? and `type` is null limit 1' at line 1 (SQL: select * from `tags` where `name`->'$."de"' = Tag1 and `type` is null limit 1)'

MariaDB 10.3.2

**Comment by TVke** [comment]
Hi @minedun6 

I just tested your code and it works.
Make sure you defined the `stories` relationship correctly and use the `HasTags` trait on your Story model.

If you want to make sure the tags are attached you can eager load them with something like this: `Story::where('name', 'testModel')->with('tags')->get()`

To @rokde and @Moppet12 a `tags` column is not present on the model itself that uses the `HasTags` trait. The tags have there own model inside the package and then get linked. 

To @rokde the exception you get is a `QueryException`. There is possible something wrong with the query so look at de laravel docs to correctly construct them at https://laravel.com/docs/5.6/eloquent.

**Comment by adamlindqvist** [comment]
@rokde according to #72 MariaDB is not supported, only MySQL.

**Comment by rokde** [comment]
Very bad news...we can not migrate to mysql back again.

**Comment by DeftNerd** [comment]
Try installing the `ybr-nx/laravel-mariadb` composer package. It fixes a lot of the slight differences between MySQL and MariaDB. I'm using `spatie/laravel-tags` successfully using MariaDB because of that package.
