### ISSUE TITLE
how to save a tag with translation

### ISSUE THREAD

**Issue by ctf0** [spatie/laravel-tags#93]
for example lets say we have
```html
<input type="text" name="name['en']">
<input type="text" name="name['fr']">
```

atm to save a tag with multi local support there are a couple of issues
- we first have to use `Tag::findOrCreate('my tag');` so we can set the translation after, which wont work with the above example
- using `Tag::Create(['name'=> $request->name]);` works but it means we have to validate for uniqueness manually

so is there a way to set the locals directly using `Tag::findOrCreate()`, maybe its not documented ?

**Comment by TVke** [comment]
Hi @ctf0 

At this moment the `findOrCreate` method is ment to find the tag or create one in the current locale of your app. If you like to explore the full documentation you can always visit [docs.spatie.be](https://docs.spatie.be/laravel-tags/v2/advanced-usage/adding-translations).

**Comment by ctf0** [comment]
@TVke i was thinking as taggable is based on translatable package, maybe the `findOrCreate` can be more global by using 2 params `input & locale` using https://github.com/spatie/laravel-translatable#validation for uniqueness test.

ex.
```php
Tag::findOrCreate($request->name, 'en')`
```

this way we save whatever the input has while deciding on which locale we want to check b4 saving.
