### ISSUE TITLE
Most popular tags

### ISSUE THREAD

**Issue by b00f** [spatie/laravel-tags#94]
Is it possible to find most popular tags on system?

**Comment by tnorthcutt** [comment]
The `taggables` table contains all instances of tags being used, so you could fairly easily write a query that gets tags ordered by the number of times they appear in the `taggables` table.

**Comment by BenQoder** [comment]
Incase someone is here looking for how to implement this, You should extend the Tags model [ See Docs ](https://docs.spatie.be/laravel-tags/v2/advanced-usage/using-your-own-tag-model) and use the code below 

```php
use Illuminate\Database\Eloquent\Builder;

....

public static function scopePopularTags(Builder $query, $type = null, $limit = null)
{
	$query = "SELECT tags.* , COUNT(tags.id) AS tagged_count FROM tags tags LEFT JOIN taggables taggables ON tags.id = taggables.tag_id"; 

	$bindings = [];

	if ($type) {
		$query .= " WHERE tags.type = ?";
		$bindings[] = $type;
	}

	$query .= " GROUP BY tags.id";

	$query .= " ORDER BY tagged_count DESC";

	if ($limit) {
		$query .= " LIMIT ?";
		$bindings[] = $limit;
	}

	return static::fromQuery($query, $bindings);
}
```

then call 

```php
YourTagModel::popularTags($tag_type, $limit)
```

**Comment by jlstandout** [comment]
How about you override Tag model and include `morphedByMany` relationship? Like this
```
use Spatie\Tags\Tag as SpatieTag;

class Tag extends SpatieTag
{
    public function items()
    {
        return $this->morphedByMany(Item::class, 'taggable');
    }
}

```
And then you can sort directly in database, like this
```
$popularTags = $tags->withCount('items')->orderBy('items_count', 'desc');
```

**Comment by techguydev** [comment]
This one worked for my adding it directly to the model that  has the tags

 public static function popularTags()
     
    {
            return DB::table('taggables')
            ->selectRaw('name,slug, count(tag_id) as tagged_count')
            ->join('tags', 'tags.id', '=', 'taggables.tag_id')
            ->groupBy('tags.id')
            ->orderBy('tagged_count', 'desc')
            ->get()

            ->map(function($tag){
                return [
                    'name' => json_decode($tag->name)->es,
                    'slug' => json_decode($tag->slug)->es,
                    'count' => $tag->tagged_count
                ];
            });
    }

**Comment by xitude** [comment]
> This one worked for my adding it directly to the model that has the tags
> 
> ```
>  public static function popularTags()
>      
>     {
>             return DB::table('taggables')
>             ->selectRaw('name,slug, count(tag_id) as tagged_count')
>             ->join('tags', 'tags.id', '=', 'taggables.tag_id')
>             ->groupBy('tags.id')
>             ->orderBy('tagged_count', 'desc')
>             ->get()
> 
>             ->map(function($tag){
>                 return [
>                     'name' => json_decode($tag->name)->es,
>                     'slug' => json_decode($tag->slug)->es,
>                     'count' => $tag->tagged_count
>                 ];
>             });
>     }
> ```

Just as a heads-up, make sure you change the `->es` to whatever lang your using.

**Comment by mohsen-zanjani** [comment]
What if we want to consider date or time?
For example, the most used or popular tags in the last month or week?

**Comment by mohsen-zanjani** [comment]
> What if we want to consider date or time? For example, the most used or popular tags in the last month or week?

For someone who also wanted to consider time or date, the following method can be used.

```php
public static function scopePopularTags(Builder $query, $type = null, $limit = null, $days = null)
{
    $query = \DB::table('taggables')
        ->selectRaw('tags.*, taggables.created_at, count(tag_id) as tagged_count')
        ->join('tags', 'tags.id', '=', 'taggables.tag_id');

    if ($type) {
        $query = $query->where('type', $type);
    }

    if ($days) {
        $query = $query->whereBetween('taggables.created_at', [now()->subdays($days), now()]);
    }

    if ($limit) {
        $query = $query->limit($limit);
    }

    return $query
        ->groupBy('tags.id')
        ->orderBy('tagged_count', 'desc')
        ->get();
}
```

Of course, you must first add the `created_at` field to the `taggables` table.

```php
$table->timestamp('created_at')->useCurrent();
```
